workspace(name = "js_image_oci")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

###
# Setup rules_js
###
local_repository(
    name = "aspect_rules_js",
    path = "../..",
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")

rules_js_dependencies()

load("@rules_nodejs//nodejs:repositories.bzl", "nodejs_register_toolchains")

nodejs_register_toolchains(
    name = "nodejs",
    node_version = "16.14.2",
)

load("@aspect_rules_js//npm:repositories.bzl", "npm_translate_lock")

npm_translate_lock(
    name = "npm",
    pnpm_lock = "//:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
)

load("@npm//:repositories.bzl", "npm_repositories")

npm_repositories()

###
# Setup rules_oci
###

http_archive(
    name = "rules_oci",
    sha256 = "08d73a9bec22642ee12c0a38c23596cbddaba7422eede74edba3bb1044d579be",
    strip_prefix = "rules_oci-1.0.0-rc0",
    url = "https://github.com/bazel-contrib/rules_oci/releases/download/v1.0.0-rc0/rules_oci-v1.0.0-rc0.tar.gz",
)

load("@rules_oci//oci:dependencies.bzl", "rules_oci_dependencies")

rules_oci_dependencies()

load("@rules_oci//oci:repositories.bzl", "LATEST_CRANE_VERSION", "oci_register_toolchains")

oci_register_toolchains(
    name = "oci",
    crane_version = LATEST_CRANE_VERSION,
)

## Pull base images
load("@rules_oci//oci:pull.bzl", "oci_pull")

oci_pull(
    name = "debian",
    digest = "sha256:63d62ae233b588d6b426b7b072d79d1306bfd02a72bff1fc045b8511cc89ee09",
    image = "debian",
    platforms = [
        "linux/386",
        "linux/amd64",
        "linux/arm/v5",
        "linux/arm/v7",
        "linux/arm64/v8",
        "linux/mips64le",
        "linux/ppc64le",
        "linux/s390x",
    ],
)

###
# Setup container_structure_test
###
http_archive(
    name = "container_structure_test",
    sha256 = "9f22497625d822afd590ea06be4f20cb7a5f5096e5a4de5edff846d56578e030",
    strip_prefix = "container-structure-test-100d7b1a8d78a79abbba996a94abe8da947742fb",
    # Note, this commit not on main, it comes from
    # https://github.com/GoogleContainerTools/container-structure-test/pull/348
    urls = ["https://github.com/GoogleContainerTools/container-structure-test/archive/100d7b1a8d78a79abbba996a94abe8da947742fb.zip"],
)

load("@container_structure_test//:repositories.bzl", "container_structure_test_register_toolchain")

container_structure_test_register_toolchain(name = "container_structure_test_toolchain")
