"""@generated by npm_translate_lock(name = "npm", pnpm_lock = "@@//root:pnpm-lock.yaml")"""

load("@npm__at_angular-devkit_core__21.2.1_chokidar_lib_chokidar__links//:defs.bzl", link_0 = "npm_link_imported_package_store_internal", store_0 = "npm_imported_package_store_internal")
load("@npm__at_aspect-test_a__5.0.2__links//:defs.bzl", link_1 = "npm_link_imported_package_store_internal", store_1 = "npm_imported_package_store_internal")
load("@npm__at_aspect-test_b__5.0.2__links//:defs.bzl", link_2 = "npm_link_imported_package_store_internal", store_2 = "npm_imported_package_store_internal")
load("@npm__at_aspect-test_c__2.0.2__links//:defs.bzl", link_3 = "npm_link_imported_package_store_internal", store_3 = "npm_imported_package_store_internal")
load("@npm__at_aspect-test_d__2.0.0_at_aspect-test_c_2.0.2__links//:defs.bzl", link_4 = "npm_link_imported_package_store_internal", store_4 = "npm_imported_package_store_internal")
load("@npm__at_aspect-test_e__1.0.0__links//:defs.bzl", link_5 = "npm_link_imported_package_store_internal", store_5 = "npm_imported_package_store_internal")
load("@npm__at_aspect-test_f__1.0.0__links//:defs.bzl", link_6 = "npm_link_imported_package_store_internal", store_6 = "npm_imported_package_store_internal")
load("@npm__at_aspect-test_g__1.0.0__links//:defs.bzl", link_7 = "npm_link_imported_package_store_internal", store_7 = "npm_imported_package_store_internal")
load("@npm__at_aspect-test_h__1.0.0__links//:defs.bzl", link_8 = "npm_link_imported_package_store_internal", store_8 = "npm_imported_package_store_internal")
load("@npm__at_types_node__22.18.13__links//:defs.bzl", link_9 = "npm_link_imported_package_store_internal", store_9 = "npm_imported_package_store_internal")
load("@npm__at_types_sizzle__2.3.8__links//:defs.bzl", link_10 = "npm_link_imported_package_store_internal", store_10 = "npm_imported_package_store_internal")
load("@npm__ajv-formats__3.0.1_ajv_8.18.0__links//:defs.bzl", store_11 = "npm_imported_package_store_internal")
load("@npm__ajv__8.18.0__links//:defs.bzl", store_12 = "npm_imported_package_store_internal")
load("@npm__fast-deep-equal__3.1.3__links//:defs.bzl", store_13 = "npm_imported_package_store_internal")
load("@npm__fast-uri__3.1.0__links//:defs.bzl", store_14 = "npm_imported_package_store_internal")
load("@npm__json-schema-traverse__1.0.0__links//:defs.bzl", store_15 = "npm_imported_package_store_internal")
load("@npm__jsonc-parser__3.3.1__links//:defs.bzl", store_16 = "npm_imported_package_store_internal")
load("@npm__lodash__file_.._vendored_lodash-4.17.19.tgz__links//:defs.bzl", link_17 = "npm_link_imported_package_store_internal", store_17 = "npm_imported_package_store_internal")
load("@npm__picomatch__4.0.3__links//:defs.bzl", store_18 = "npm_imported_package_store_internal")
load("@npm__require-from-string__2.0.2__links//:defs.bzl", store_19 = "npm_imported_package_store_internal")
load("@npm__rxjs__7.8.2__links//:defs.bzl", store_20 = "npm_imported_package_store_internal")
load("@npm__source-map__0.7.6__links//:defs.bzl", store_21 = "npm_imported_package_store_internal")
load("@npm__tslib__2.8.1__links//:defs.bzl", store_22 = "npm_imported_package_store_internal")
load("@npm__typescript__5.9.3__links//:defs.bzl", link_23 = "npm_link_imported_package_store_internal", store_23 = "npm_imported_package_store_internal")
load("@npm__undici-types__6.21.0__links//:defs.bzl", store_24 = "npm_imported_package_store_internal")

# buildifier: disable=bzl-visibility
load("@aspect_rules_js//js:defs.bzl", _js_library = "js_library")

# buildifier: disable=bzl-visibility
load("@aspect_rules_js//npm/private:npm_link_package_store.bzl", _npm_local_link_package_store = "npm_local_link_package_store_internal")

# buildifier: disable=bzl-visibility
load("@aspect_rules_js//npm/private:npm_package_store.bzl", _npm_local_package_store = "npm_local_package_store_internal")

_IMPORTER_PACKAGES = ["root", "", "app/a", "app/b", "app/c", "app/d", "lib/a", "lib/b", "lib/c", "lib/chokidar", "lib/d"]

# buildifier: disable=function-docstring
def npm_link_all_packages(name = "node_modules", imported_links = [], prod = True, dev = True):
    if name != "node_modules":
        fail("npm_link_all_packages: customizing 'name' is not supported")
    if not prod and not dev:
        fail("npm_link_all_packages: at least one of 'prod' or 'dev' must be True")

    bazel_package = native.package_name()
    root_package = "root"
    is_root = bazel_package == root_package
    is_importer = bazel_package in _IMPORTER_PACKAGES
    if not is_root and not is_importer:
        msg = "The npm_link_all_packages() macro loaded from @npm//:defs.bzl and called in bazel package '%s' may only be called in bazel packages that correspond to the pnpm root package or pnpm workspace projects. Projects are discovered from the pnpm-lock.yaml and may be missing if the lockfile is out of date. Root package: 'root', pnpm workspace projects: %s" % (bazel_package, "'" + "', '".join(_IMPORTER_PACKAGES) + "'")
        fail(msg)

    if is_root:
        store_0()
        store_1()
        store_2()
        store_3()
        store_4()
        store_5()
        store_6()
        store_7()
        store_8()
        store_9()
        store_10()
        store_11()
        store_12()
        store_13()
        store_14()
        store_15()
        store_16()
        store_17()
        store_18()
        store_19()
        store_20()
        store_21()
        store_22()
        store_23()
        store_24()
        _npm_local_package_store(
            package_store_name = "vendored-a@file+..+vendored+a",
            src = "//vendored/a:pkg",
            package = "vendored-a",
            version = "file:../vendored/a",
            deps = {
                "//root:.aspect_rules_js/node_modules/@aspect-test+f@1.0.0": "@aspect-test/f",
            },
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )
        _npm_local_package_store(
            package_store_name = "vendored-b@file+..+vendored+b_@lib+b@lib+b",
            src = "//vendored/b:pkg",
            package = "vendored-b",
            version = "file:../vendored/b(@lib/b@lib+b)",
            deps = {
                "//root:.aspect_rules_js/node_modules/@lib+b@0.0.0": "@lib/b",
            },
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )
        _npm_local_package_store(
            package_store_name = "chokidar@0.0.0",
            src = "//lib/chokidar:pkg",
            package = "chokidar",
            version = "0.0.0",
            deps = {},
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )
        _npm_local_package_store(
            package_store_name = "@lib+a@0.0.0",
            src = "//lib/a:pkg",
            package = "@lib/a",
            version = "0.0.0",
            deps = {
                "//root:.aspect_rules_js/node_modules/@aspect-test+e@1.0.0": "@aspect-test/e",
                "//root:.aspect_rules_js/node_modules/@lib+b@0.0.0": "@lib/b",
                "//root:.aspect_rules_js/node_modules/vendored-a@file+..+vendored+a": "vendored-a",
                "//root:.aspect_rules_js/node_modules/vendored-b@file+..+vendored+b_@lib+b@lib+b": "vendored-b",
            },
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )
        _npm_local_package_store(
            package_store_name = "@lib+b@0.0.0",
            src = "//lib/b:pkg",
            package = "@lib/b",
            version = "0.0.0",
            deps = {
                "//root:.aspect_rules_js/node_modules/@aspect-test+f@1.0.0": "@aspect-test/f",
                "//root:.aspect_rules_js/node_modules/@types+sizzle@2.3.8": "alias-1",
            },
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )
        _npm_local_package_store(
            package_store_name = "@lib+c@0.0.0",
            src = "//lib/c:pkg",
            package = "@lib/c",
            version = "0.0.0",
            deps = {
                "//root:.aspect_rules_js/node_modules/@aspect-test+f@1.0.0": "@aspect-test/f",
            },
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )
        _npm_local_package_store(
            package_store_name = "@lib+d@0.0.0",
            src = "//lib/d:pkg",
            package = "@lib/d",
            version = "0.0.0",
            deps = {
                "//root:.aspect_rules_js/node_modules/@aspect-test+d@2.0.0_@aspect-test+c@2.0.2": "@aspect-test/d",
                "//root:.aspect_rules_js/node_modules/@types+node@22.18.13": "alias-2",
            },
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

    link_targets = None
    scope_targets = None

    if is_importer:
        if bazel_package == "":
            link_0()
            link_1()
            link_2(dev=True)
            link_3()
            link_17()
            link_23()
            _fp_link_2()
            link_targets = [
                ":node_modules/@angular-devkit/core",
                ":node_modules/@aspect-test/a",
                ":node_modules/@aspect-test/c",
                ":node_modules/lodash",
                ":node_modules/typescript",
                ":node_modules/chokidar",
                ":node_modules/@aspect-test/b",
            ]
            scope_targets = {
                "@angular-devkit": [":node_modules/@angular-devkit/core"],
                "@aspect-test": [
                    ":node_modules/@aspect-test/a",
                    ":node_modules/@aspect-test/b",
                    ":node_modules/@aspect-test/c",
                ],
            }
        elif bazel_package == "app/a":
            link_1()
            link_7()
            _fp_link_3()
            link_targets = [
                ":node_modules/@aspect-test/a",
                ":node_modules/@aspect-test/g",
                ":node_modules/@lib/a",
            ]
            scope_targets = {
                "@aspect-test": [
                    ":node_modules/@aspect-test/a",
                    ":node_modules/@aspect-test/g",
                ],
                "@lib": [":node_modules/@lib/a"],
            }
        elif bazel_package == "app/c":
            link_1()
            link_7()
            _fp_link_5()
            link_targets = [
                ":node_modules/@aspect-test/a",
                ":node_modules/@aspect-test/g",
                ":node_modules/@lib/c",
            ]
            scope_targets = {
                "@aspect-test": [
                    ":node_modules/@aspect-test/a",
                    ":node_modules/@aspect-test/g",
                ],
                "@lib": [":node_modules/@lib/c"],
            }
        elif bazel_package == "lib/d":
            link_4()
            link_9("alias-2")
            link_targets = [
                ":node_modules/@aspect-test/d",
                ":node_modules/alias-2",
            ]
            scope_targets = {
                "@aspect-test": [":node_modules/@aspect-test/d"],
            }
        elif bazel_package == "lib/a":
            link_5()
            _fp_link_0()
            _fp_link_1()
            _fp_link_4()
            link_targets = [
                ":node_modules/@aspect-test/e",
                ":node_modules/vendored-a",
                ":node_modules/vendored-b",
                ":node_modules/@lib/b",
            ]
            scope_targets = {
                "@aspect-test": [":node_modules/@aspect-test/e"],
                "@lib": [":node_modules/@lib/b"],
            }
        elif bazel_package == "lib/b":
            link_6()
            link_10("alias-1")
            link_targets = [
                ":node_modules/@aspect-test/f",
                ":node_modules/alias-1",
            ]
            scope_targets = {
                "@aspect-test": [":node_modules/@aspect-test/f"],
            }
        elif bazel_package == "lib/c":
            link_6()
            link_targets = [":node_modules/@aspect-test/f"]
            scope_targets = {
                "@aspect-test": [":node_modules/@aspect-test/f"],
            }
        elif bazel_package == "app/d":
            link_7()
            _fp_link_6()
            link_targets = [
                ":node_modules/@aspect-test/g",
                ":node_modules/@lib/d",
            ]
            scope_targets = {
                "@aspect-test": [":node_modules/@aspect-test/g"],
                "@lib": [":node_modules/@lib/d"],
            }
        elif bazel_package == "app/b":
            link_8()
            _fp_link_4()
            _fp_link_4("@lib/b_alias")
            link_targets = [
                ":node_modules/@aspect-test/h",
                ":node_modules/@lib/b",
                ":node_modules/@lib/b_alias",
            ]
            scope_targets = {
                "@aspect-test": [":node_modules/@aspect-test/h"],
                "@lib": [
                    ":node_modules/@lib/b",
                    ":node_modules/@lib/b_alias",
                ],
            }
    for link_fn in imported_links:
        new_link_targets, new_scope_targets = link_fn(name, prod, dev)
        if not link_targets:
            link_targets = []
        link_targets.extend(new_link_targets)
        for _scope, _targets in new_scope_targets.items():
            if not scope_targets:
                scope_targets = {}
            if _scope not in scope_targets:
                scope_targets[_scope] = []
            scope_targets[_scope].extend(_targets)

    if scope_targets:
        for scope, scoped_targets in scope_targets.items():
            _js_library(
                name = "node_modules/{}".format(scope),
                srcs = scoped_targets,
                tags = ["manual"],
                visibility = ["//visibility:public"],
            )

    if is_importer:
        _js_library(
            name = "node_modules",
            srcs = link_targets if link_targets else [],
            tags = ["manual"],
            visibility = ["//visibility:public"],
        )

# buildifier: disable=function-docstring
def npm_link_targets(name = "node_modules", package = None, prod = True, dev = True):
    if name != "node_modules":
        fail("npm_link_targets: customizing 'name' is not supported")
    if not prod and not dev:
        fail("npm_link_targets: at least one of 'prod' or 'dev' must be True")

    bazel_package = package if package != None else native.package_name()

    link_targets = []

    if bazel_package == "":
        if prod:
            link_targets.extend([
                ":node_modules/@angular-devkit/core",
                ":node_modules/@aspect-test/a",
                ":node_modules/@aspect-test/c",
                ":node_modules/lodash",
                ":node_modules/typescript",
                ":node_modules/chokidar",
            ])
        if dev:
            link_targets.extend([":node_modules/@aspect-test/b"])
    elif bazel_package == "app/a":
        if prod:
            link_targets.extend([
                ":node_modules/@aspect-test/a",
                ":node_modules/@aspect-test/g",
                ":node_modules/@lib/a",
            ])
    elif bazel_package == "app/c":
        if prod:
            link_targets.extend([
                ":node_modules/@aspect-test/a",
                ":node_modules/@aspect-test/g",
                ":node_modules/@lib/c",
            ])
    elif bazel_package == "lib/d":
        if prod:
            link_targets.extend([
                ":node_modules/@aspect-test/d",
                ":node_modules/alias-2",
            ])
    elif bazel_package == "lib/a":
        if prod:
            link_targets.extend([
                ":node_modules/@aspect-test/e",
                ":node_modules/vendored-a",
                ":node_modules/vendored-b",
                ":node_modules/@lib/b",
            ])
    elif bazel_package == "lib/b":
        if prod:
            link_targets.extend([
                ":node_modules/@aspect-test/f",
                ":node_modules/alias-1",
            ])
    elif bazel_package == "lib/c":
        if prod:
            link_targets.extend([":node_modules/@aspect-test/f"])
    elif bazel_package == "app/d":
        if prod:
            link_targets.extend([
                ":node_modules/@aspect-test/g",
                ":node_modules/@lib/d",
            ])
    elif bazel_package == "app/b":
        if prod:
            link_targets.extend([
                ":node_modules/@aspect-test/h",
                ":node_modules/@lib/b",
                ":node_modules/@lib/b_alias",
            ])
    return ["//%s%s" % (bazel_package, target) for target in link_targets]

# Generated npm_link_package_store for linking of first-party "vendored-a" package
# buildifier: disable=function-docstring
def _fp_link_0(alias = None):
    _npm_local_link_package_store(
        name = "node_modules/vendored-a" if alias == None else "node_modules/{}".format(alias),
        package = alias,
        src = "//root:.aspect_rules_js/node_modules/vendored-a@file+..+vendored+a",
    )

# Generated npm_link_package_store for linking of first-party "vendored-b" package
# buildifier: disable=function-docstring
def _fp_link_1(alias = None):
    _npm_local_link_package_store(
        name = "node_modules/vendored-b" if alias == None else "node_modules/{}".format(alias),
        package = alias,
        src = "//root:.aspect_rules_js/node_modules/vendored-b@file+..+vendored+b_@lib+b@lib+b",
    )

# Generated npm_link_package_store for linking of first-party "chokidar" package
# buildifier: disable=function-docstring
def _fp_link_2(alias = None):
    _npm_local_link_package_store(
        name = "node_modules/chokidar" if alias == None else "node_modules/{}".format(alias),
        package = alias,
        src = "//root:.aspect_rules_js/node_modules/chokidar@0.0.0",
    )

# Generated npm_link_package_store for linking of first-party "@lib/a" package
# buildifier: disable=function-docstring
def _fp_link_3(alias = None):
    _npm_local_link_package_store(
        name = "node_modules/@lib/a" if alias == None else "node_modules/{}".format(alias),
        package = alias,
        src = "//root:.aspect_rules_js/node_modules/@lib+a@0.0.0",
    )

# Generated npm_link_package_store for linking of first-party "@lib/b" package
# buildifier: disable=function-docstring
def _fp_link_4(alias = None):
    _npm_local_link_package_store(
        name = "node_modules/@lib/b" if alias == None else "node_modules/{}".format(alias),
        package = alias,
        src = "//root:.aspect_rules_js/node_modules/@lib+b@0.0.0",
    )

# Generated npm_link_package_store for linking of first-party "@lib/c" package
# buildifier: disable=function-docstring
def _fp_link_5(alias = None):
    _npm_local_link_package_store(
        name = "node_modules/@lib/c" if alias == None else "node_modules/{}".format(alias),
        package = alias,
        src = "//root:.aspect_rules_js/node_modules/@lib+c@0.0.0",
    )

# Generated npm_link_package_store for linking of first-party "@lib/d" package
# buildifier: disable=function-docstring
def _fp_link_6(alias = None):
    _npm_local_link_package_store(
        name = "node_modules/@lib/d" if alias == None else "node_modules/{}".format(alias),
        package = alias,
        src = "//root:.aspect_rules_js/node_modules/@lib+d@0.0.0",
    )
