local_repository(
    name = "aspect_rules_js",
    path = "../..",
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")

rules_js_dependencies()

load("@aspect_rules_js//js:toolchains.bzl", "rules_js_register_toolchains")

# nodejs 14 is used intentionally here, to assert AbortController polyfill is installed properly.
rules_js_register_toolchains(node_version = "14.20.0")
