"@generated by @aspect_rules_js//npm/private:npm_import.bzl for npm package @aspect-test/a@5.0.2"

# buildifier: disable=bzl-visibility
load("@aspect_rules_js//npm/private:npm_package_store_internal.bzl", _npm_package_store = "npm_package_store_internal")

# buildifier: disable=bzl-visibility
load("@aspect_rules_js//npm/private:npm_import.bzl",
    _npm_imported_package_store = "npm_imported_package_store_internal",
    _npm_link_imported_package = "npm_link_imported_package_internal",
    _npm_link_imported_package_store = "npm_link_imported_package_store_internal")

PACKAGE = "@aspect-test/a"
VERSION = "5.0.2"
_ROOT_PACKAGE = "<LOCKVERSION>"
_PACKAGE_STORE_NAME = "@aspect-test+a@5.0.2"

# Generated npm_package_store targets for npm package @aspect-test/a@5.0.2
# buildifier: disable=function-docstring
def npm_imported_package_store():
    _npm_imported_package_store(
        package = PACKAGE,
        version = VERSION,
        root_package = _ROOT_PACKAGE,
        deps = {
            ":.aspect_rules_js/node_modules/@aspect-test+a@5.0.2/pkg": "@aspect-test/a",
            ":.aspect_rules_js/node_modules/@aspect-test+b@5.0.2/pkg": "@aspect-test/b",
            ":.aspect_rules_js/node_modules/@aspect-test+c@2.0.2/pkg": "@aspect-test/c",
            ":.aspect_rules_js/node_modules/@aspect-test+d@2.0.0_at_aspect-test_c_2.0.2/pkg": "@aspect-test/d",
        },
        ref_deps = {
            ":.aspect_rules_js/node_modules/@aspect-test+b@5.0.2/ref": "@aspect-test/b",
            ":.aspect_rules_js/node_modules/@aspect-test+c@2.0.2/ref": "@aspect-test/c",
            ":.aspect_rules_js/node_modules/@aspect-test+d@2.0.0_at_aspect-test_c_2.0.2/ref": "@aspect-test/d",
        },
        lc_deps = {
            ":.aspect_rules_js/node_modules/@aspect-test+a@5.0.2/pkg_pre_lc_lite": "@aspect-test/a",
            ":.aspect_rules_js/node_modules/@aspect-test+b@5.0.2/pkg": "@aspect-test/b",
            ":.aspect_rules_js/node_modules/@aspect-test+c@2.0.2/pkg": "@aspect-test/c",
            ":.aspect_rules_js/node_modules/@aspect-test+d@2.0.0_at_aspect-test_c_2.0.2/pkg": "@aspect-test/d",
        },
        has_lifecycle_build_target = False,
        transitive_closure_pattern = True,
        npm_package_target = "@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_aspect-test_a__5.0.2//:pkg",
        package_store_name = _PACKAGE_STORE_NAME,
        lifecycle_hooks_env = {},
        lifecycle_hooks_execution_requirements = {},
        use_default_shell_env = False,
        exclude_package_contents = [],
    )

# Generated npm_package_store and npm_link_package_store targets for npm package @aspect-test/a@5.0.2
# buildifier: disable=function-docstring
def npm_link_imported_package_store(name, dev, link_alias):
    return _npm_link_imported_package_store(
        name,
        dev,
        link_alias,
        root_package = _ROOT_PACKAGE,
        link_visibility = ["//visibility:public"],
        bins = {},
        package_store_name = _PACKAGE_STORE_NAME,
        public_visibility = True,
    )

# Generated npm_package_store and npm_link_package_store targets for npm package @aspect-test/a@5.0.2
# buildifier: disable=function-docstring
def npm_link_imported_package(
        name = "node_modules",
        dev = False,
        link = None):
    if name != "node_modules":
        fail("npm_link_imported_package: customizing 'name' is not supported")
    return _npm_link_imported_package(
        package = PACKAGE,
        version = VERSION,
        dev = dev,
        root_package = _ROOT_PACKAGE,
        link = link,
        link_packages = {
            "<LOCKVERSION>": ["@aspect-test-a-bad-scope", "@aspect-test-custom-scope/a", "@aspect-test/a", "@aspect-test/a2", "aspect-test-a-no-scope", "aspect-test-a/no-at"],
        },
        public_visibility = True,
        npm_link_imported_package_store_macro = npm_link_imported_package_store,
        npm_imported_package_store_macro = npm_imported_package_store,
    )
