"@generated by @aspect_rules_js//npm/private:npm_import.bzl for npm package lodash@file:../vendored/lodash-4.17.21.tgz"

# buildifier: disable=bzl-visibility
load(
    "@aspect_rules_js//npm/private:npm_import.bzl",
    _npm_imported_package_store_internal = "npm_imported_package_store_internal",
    _npm_link_imported_package_internal = "npm_link_imported_package_internal",
    _npm_link_imported_package_store_internal = "npm_link_imported_package_store_internal",
)

PACKAGE = "lodash"
VERSION = "file:../vendored/lodash-4.17.21.tgz"
_ROOT_PACKAGE = "<LOCKVERSION>"
_KEY = "lodash@file:../vendored/lodash-4.17.21.tgz"
_PACKAGE_STORE_NAME = "lodash@file+..+vendored+lodash-4.17.21.tgz"

# Generated npm_imported_package_store_internal() wrapper target for npm package lodash@file:../vendored/lodash-4.17.21.tgz
# buildifier: disable=function-docstring
def npm_imported_package_store_internal():
    _npm_imported_package_store_internal(
        key = _KEY,
        package = PACKAGE,
        version = VERSION,
        root_package = _ROOT_PACKAGE,
        deps = {},
        ref_deps = {},
        lc_deps = {},
        has_lifecycle_build_target = False,
        has_transitive_closure = False,
        npm_package_target = "@@aspect_rules_js~~npm~lock-<LOCKVERSION>__lodash__file_.._vendored_lodash-4.17.21.tgz//:pkg",
        package_store_name = _PACKAGE_STORE_NAME,
        lifecycle_hooks_env = {},
        lifecycle_hooks_execution_requirements = {},
        use_default_shell_env = False,
        exclude_package_contents = [
    "**/__tests__/**",
    "**/test/**",
    "**/tests/**",
    "**/powered-test/**",
    "**/docs/**",
    "**/doc/**",
    "**/website/**",
    "**/images/**",
    "**/assets/**",
    "**/example/**",
    "**/examples/**",
    "**/coverage/**",
    "**/.nyc_output/**",
    "Makefile",
    "Gulpfile.js",
    "Gruntfile.js",
    "appveyor.yml",
    "circle.yml",
    "codeship-services.yml",
    "codeship-steps.yml",
    "wercker.yml",
    ".tern-project",
    ".gitattributes",
    ".editorconfig",
    ".*ignore",
    ".eslintrc",
    ".jshintrc",
    ".flowconfig",
    ".documentup.json",
    ".yarn-metadata.json",
    ".travis.yml",
    "*.md",
],
    )

# Generated npm_link_imported_package_store_internal() for npm package lodash@file:../vendored/lodash-4.17.21.tgz
# buildifier: disable=function-docstring
def npm_link_imported_package_store_internal(link_name = PACKAGE, dev = False):
    _npm_link_imported_package_store_internal(
        link_name,
        dev,
        root_package = _ROOT_PACKAGE,
        link_visibility = ["//visibility:public"],
        bins = {},
        package_store_name = _PACKAGE_STORE_NAME,
    )

# Generated public npm_package_store() and npm_link_package_store() targets for npm package lodash@file:../vendored/lodash-4.17.21.tgz
# buildifier: disable=function-docstring
def npm_link_imported_package(
        name = "node_modules",
        dev = False,
        link = True):
    return _npm_link_imported_package_internal(
        name,
        package = PACKAGE,
        version = VERSION,
        dev = dev,
        root_package = _ROOT_PACKAGE,
        link = link,
        public_visibility = True,
        npm_link_imported_package_store_macro = npm_link_imported_package_store_internal,
        npm_imported_package_store_macro = npm_imported_package_store_internal,
    )
