"@generated by @aspect_rules_js//npm/private:npm_import.bzl for npm package next@15.2.4(@babel/core@7.28.5)(react-dom@19.2.0(react@19.2.0))(react@19.2.0)"

# buildifier: disable=bzl-visibility
load(
    "@aspect_rules_js//npm/private:npm_import.bzl",
    _npm_imported_package_store_internal = "npm_imported_package_store_internal",
    _npm_link_imported_package_internal = "npm_link_imported_package_internal",
    _npm_link_imported_package_store_internal = "npm_link_imported_package_store_internal",
)

PACKAGE = "next"
VERSION = "15.2.4(@babel/core@7.28.5)(react-dom@19.2.0(react@19.2.0))(react@19.2.0)"
_ROOT_PACKAGE = ""
_KEY = "next@15.2.4(@babel/core@7.28.5)(react-dom@19.2.0(react@19.2.0))(react@19.2.0)"
_PACKAGE_STORE_NAME = "next@15.2.4_1790925128"

# Generated npm_imported_package_store_internal() wrapper target for npm package next@15.2.4(@babel/core@7.28.5)(react-dom@19.2.0(react@19.2.0))(react@19.2.0)
# buildifier: disable=function-docstring
def npm_imported_package_store_internal():
    _npm_imported_package_store_internal(
        key = _KEY,
        package = PACKAGE,
        version = VERSION,
        root_package = _ROOT_PACKAGE,
        deps = {
            ":.aspect_rules_js/node_modules/next@15.2.4_1790925128/pkg": "next",
            ":.aspect_rules_js/node_modules/@next+env@15.2.4/pkg": "@next/env",
            ":.aspect_rules_js/node_modules/@swc+counter@0.1.3/pkg": "@swc/counter",
            ":.aspect_rules_js/node_modules/@swc+helpers@0.5.15/pkg": "@swc/helpers",
            ":.aspect_rules_js/node_modules/busboy@1.6.0/pkg": "busboy",
            ":.aspect_rules_js/node_modules/caniuse-lite@1.0.30001752/pkg": "caniuse-lite",
            ":.aspect_rules_js/node_modules/client-only@0.0.1/pkg": "client-only",
            ":.aspect_rules_js/node_modules/nanoid@3.3.11/pkg": "nanoid",
            ":.aspect_rules_js/node_modules/picocolors@1.1.1/pkg": "picocolors",
            ":.aspect_rules_js/node_modules/postcss@8.4.31/pkg": "postcss",
            ":.aspect_rules_js/node_modules/react-dom@19.2.0_react@19.2.0/pkg": "react-dom",
            ":.aspect_rules_js/node_modules/react@19.2.0/pkg": "react",
            ":.aspect_rules_js/node_modules/scheduler@0.27.0/pkg": "scheduler",
            ":.aspect_rules_js/node_modules/source-map-js@1.2.1/pkg": "source-map-js",
            ":.aspect_rules_js/node_modules/streamsearch@1.1.0/pkg": "streamsearch",
            ":.aspect_rules_js/node_modules/styled-jsx@5.1.6_324456147/pkg": "styled-jsx",
            ":.aspect_rules_js/node_modules/tslib@2.8.1/pkg": "tslib",
            ":.aspect_rules_js/node_modules/@babel+code-frame@7.27.1/pkg": "@babel/code-frame",
            ":.aspect_rules_js/node_modules/@babel+compat-data@7.28.5/pkg": "@babel/compat-data",
            ":.aspect_rules_js/node_modules/@babel+core@7.28.5/pkg": "@babel/core",
            ":.aspect_rules_js/node_modules/@babel+generator@7.28.5/pkg": "@babel/generator",
            ":.aspect_rules_js/node_modules/@babel+helper-compilation-targets@7.27.2/pkg": "@babel/helper-compilation-targets",
            ":.aspect_rules_js/node_modules/@babel+helper-globals@7.28.0/pkg": "@babel/helper-globals",
            ":.aspect_rules_js/node_modules/@babel+helper-module-imports@7.27.1/pkg": "@babel/helper-module-imports",
            ":.aspect_rules_js/node_modules/@babel+helper-module-transforms@7.28.3_@babel+core@7.28.5/pkg": "@babel/helper-module-transforms",
            ":.aspect_rules_js/node_modules/@babel+helper-string-parser@7.27.1/pkg": "@babel/helper-string-parser",
            ":.aspect_rules_js/node_modules/@babel+helper-validator-identifier@7.28.5/pkg": "@babel/helper-validator-identifier",
            ":.aspect_rules_js/node_modules/@babel+helper-validator-option@7.27.1/pkg": "@babel/helper-validator-option",
            ":.aspect_rules_js/node_modules/@babel+helpers@7.28.4/pkg": "@babel/helpers",
            ":.aspect_rules_js/node_modules/@babel+parser@7.28.5/pkg": "@babel/parser",
            ":.aspect_rules_js/node_modules/@babel+template@7.27.2/pkg": "@babel/template",
            ":.aspect_rules_js/node_modules/@babel+traverse@7.28.5/pkg": "@babel/traverse",
            ":.aspect_rules_js/node_modules/@babel+types@7.28.5/pkg": "@babel/types",
            ":.aspect_rules_js/node_modules/@emnapi+runtime@1.6.0/pkg": "@emnapi/runtime",
            ":.aspect_rules_js/node_modules/@jridgewell+gen-mapping@0.3.13/pkg": "@jridgewell/gen-mapping",
            ":.aspect_rules_js/node_modules/@jridgewell+remapping@2.3.5/pkg": "@jridgewell/remapping",
            ":.aspect_rules_js/node_modules/@jridgewell+resolve-uri@3.1.2/pkg": "@jridgewell/resolve-uri",
            ":.aspect_rules_js/node_modules/@jridgewell+sourcemap-codec@1.5.5/pkg": "@jridgewell/sourcemap-codec",
            ":.aspect_rules_js/node_modules/@jridgewell+trace-mapping@0.3.31/pkg": "@jridgewell/trace-mapping",
            ":.aspect_rules_js/node_modules/baseline-browser-mapping@2.8.23/pkg": "baseline-browser-mapping",
            ":.aspect_rules_js/node_modules/browserslist@4.27.0/pkg": "browserslist",
            ":.aspect_rules_js/node_modules/color-convert@2.0.1/pkg": "color-convert",
            ":.aspect_rules_js/node_modules/color-name@1.1.4/pkg": "color-name",
            ":.aspect_rules_js/node_modules/color-string@1.9.1/pkg": "color-string",
            ":.aspect_rules_js/node_modules/color@4.2.3/pkg": "color",
            ":.aspect_rules_js/node_modules/convert-source-map@2.0.0/pkg": "convert-source-map",
            ":.aspect_rules_js/node_modules/debug@4.4.3/pkg": "debug",
            ":.aspect_rules_js/node_modules/detect-libc@2.1.2/pkg": "detect-libc",
            ":.aspect_rules_js/node_modules/electron-to-chromium@1.5.244/pkg": "electron-to-chromium",
            ":.aspect_rules_js/node_modules/escalade@3.2.0/pkg": "escalade",
            ":.aspect_rules_js/node_modules/gensync@1.0.0-beta.2/pkg": "gensync",
            ":.aspect_rules_js/node_modules/is-arrayish@0.3.4/pkg": "is-arrayish",
            ":.aspect_rules_js/node_modules/js-tokens@4.0.0/pkg": "js-tokens",
            ":.aspect_rules_js/node_modules/jsesc@3.1.0/pkg": "jsesc",
            ":.aspect_rules_js/node_modules/json5@2.2.3/pkg": "json5",
            ":.aspect_rules_js/node_modules/lru-cache@5.1.1/pkg": "lru-cache",
            ":.aspect_rules_js/node_modules/ms@2.1.3/pkg": "ms",
            ":.aspect_rules_js/node_modules/node-releases@2.0.27/pkg": "node-releases",
            ":.aspect_rules_js/node_modules/semver@6.3.1/pkg": "semver",
            ":.aspect_rules_js/node_modules/semver@7.7.3/pkg": "semver",
            ":.aspect_rules_js/node_modules/sharp@0.33.5/pkg": "sharp",
            ":.aspect_rules_js/node_modules/simple-swizzle@0.2.4/pkg": "simple-swizzle",
            ":.aspect_rules_js/node_modules/update-browserslist-db@1.1.4_browserslist@4.27.0/pkg": "update-browserslist-db",
            ":.aspect_rules_js/node_modules/yallist@3.1.1/pkg": "yallist",
        } | select({
            "@aspect_rules_js//platforms/pnpm:darwin_arm64": {
                ":.aspect_rules_js/node_modules/@img+sharp-darwin-arm64@0.33.5/pkg": "@img/sharp-darwin-arm64",
                ":.aspect_rules_js/node_modules/@img+sharp-libvips-darwin-arm64@1.0.4/pkg": "@img/sharp-libvips-darwin-arm64",
                ":.aspect_rules_js/node_modules/@next+swc-darwin-arm64@15.2.4/pkg": "@next/swc-darwin-arm64",
            },
            "@aspect_rules_js//platforms/pnpm:darwin_x64": {
                ":.aspect_rules_js/node_modules/@img+sharp-darwin-x64@0.33.5/pkg": "@img/sharp-darwin-x64",
                ":.aspect_rules_js/node_modules/@img+sharp-libvips-darwin-x64@1.0.4/pkg": "@img/sharp-libvips-darwin-x64",
                ":.aspect_rules_js/node_modules/@next+swc-darwin-x64@15.2.4/pkg": "@next/swc-darwin-x64",
            },
            "@aspect_rules_js//platforms/pnpm:linux_arm64": {
                ":.aspect_rules_js/node_modules/@img+sharp-libvips-linux-arm64@1.0.4/pkg": "@img/sharp-libvips-linux-arm64",
                ":.aspect_rules_js/node_modules/@img+sharp-libvips-linuxmusl-arm64@1.0.4/pkg": "@img/sharp-libvips-linuxmusl-arm64",
                ":.aspect_rules_js/node_modules/@img+sharp-linux-arm64@0.33.5/pkg": "@img/sharp-linux-arm64",
                ":.aspect_rules_js/node_modules/@img+sharp-linuxmusl-arm64@0.33.5/pkg": "@img/sharp-linuxmusl-arm64",
                ":.aspect_rules_js/node_modules/@next+swc-linux-arm64-gnu@15.2.4/pkg": "@next/swc-linux-arm64-gnu",
                ":.aspect_rules_js/node_modules/@next+swc-linux-arm64-musl@15.2.4/pkg": "@next/swc-linux-arm64-musl",
            },
            "@aspect_rules_js//platforms/pnpm:linux_arm": {
                ":.aspect_rules_js/node_modules/@img+sharp-libvips-linux-arm@1.0.5/pkg": "@img/sharp-libvips-linux-arm",
                ":.aspect_rules_js/node_modules/@img+sharp-linux-arm@0.33.5/pkg": "@img/sharp-linux-arm",
            },
            "@aspect_rules_js//platforms/pnpm:linux_s390x": {
                ":.aspect_rules_js/node_modules/@img+sharp-libvips-linux-s390x@1.0.4/pkg": "@img/sharp-libvips-linux-s390x",
                ":.aspect_rules_js/node_modules/@img+sharp-linux-s390x@0.33.5/pkg": "@img/sharp-linux-s390x",
            },
            "@aspect_rules_js//platforms/pnpm:linux_x64": {
                ":.aspect_rules_js/node_modules/@img+sharp-libvips-linux-x64@1.0.4/pkg": "@img/sharp-libvips-linux-x64",
                ":.aspect_rules_js/node_modules/@img+sharp-libvips-linuxmusl-x64@1.0.4/pkg": "@img/sharp-libvips-linuxmusl-x64",
                ":.aspect_rules_js/node_modules/@img+sharp-linux-x64@0.33.5/pkg": "@img/sharp-linux-x64",
                ":.aspect_rules_js/node_modules/@img+sharp-linuxmusl-x64@0.33.5/pkg": "@img/sharp-linuxmusl-x64",
                ":.aspect_rules_js/node_modules/@next+swc-linux-x64-gnu@15.2.4/pkg": "@next/swc-linux-x64-gnu",
                ":.aspect_rules_js/node_modules/@next+swc-linux-x64-musl@15.2.4/pkg": "@next/swc-linux-x64-musl",
            },
            "@aspect_rules_js//platforms/pnpm:wasm32": {
                ":.aspect_rules_js/node_modules/@img+sharp-wasm32@0.33.5/pkg": "@img/sharp-wasm32",
            },
            "@aspect_rules_js//platforms/pnpm:win32_ia32": {
                ":.aspect_rules_js/node_modules/@img+sharp-win32-ia32@0.33.5/pkg": "@img/sharp-win32-ia32",
            },
            "@aspect_rules_js//platforms/pnpm:win32_x64": {
                ":.aspect_rules_js/node_modules/@img+sharp-win32-x64@0.33.5/pkg": "@img/sharp-win32-x64",
                ":.aspect_rules_js/node_modules/@next+swc-win32-x64-msvc@15.2.4/pkg": "@next/swc-win32-x64-msvc",
            },
            "@aspect_rules_js//platforms/pnpm:win32_arm64": {
                ":.aspect_rules_js/node_modules/@next+swc-win32-arm64-msvc@15.2.4/pkg": "@next/swc-win32-arm64-msvc",
            },
            "//conditions:default": {},
        }),
        ref_deps = {
            ":.aspect_rules_js/node_modules/@next+env@15.2.4/ref": "@next/env",
            ":.aspect_rules_js/node_modules/@swc+counter@0.1.3/ref": "@swc/counter",
            ":.aspect_rules_js/node_modules/@swc+helpers@0.5.15/ref": "@swc/helpers",
            ":.aspect_rules_js/node_modules/busboy@1.6.0/ref": "busboy",
            ":.aspect_rules_js/node_modules/caniuse-lite@1.0.30001752/ref": "caniuse-lite",
            ":.aspect_rules_js/node_modules/postcss@8.4.31/ref": "postcss",
            ":.aspect_rules_js/node_modules/react@19.2.0/ref": "react",
            ":.aspect_rules_js/node_modules/react-dom@19.2.0_react@19.2.0/ref": "react-dom",
            ":.aspect_rules_js/node_modules/styled-jsx@5.1.6_324456147/ref": "styled-jsx",
            ":.aspect_rules_js/node_modules/sharp@0.33.5/ref": "sharp",
        } | select({
            "@aspect_rules_js//platforms/pnpm:darwin_arm64": {
                ":.aspect_rules_js/node_modules/@next+swc-darwin-arm64@15.2.4/ref": "@next/swc-darwin-arm64",
            },
            "@aspect_rules_js//platforms/pnpm:darwin_x64": {
                ":.aspect_rules_js/node_modules/@next+swc-darwin-x64@15.2.4/ref": "@next/swc-darwin-x64",
            },
            "@aspect_rules_js//platforms/pnpm:linux_arm64": {
                ":.aspect_rules_js/node_modules/@next+swc-linux-arm64-gnu@15.2.4/ref": "@next/swc-linux-arm64-gnu",
                ":.aspect_rules_js/node_modules/@next+swc-linux-arm64-musl@15.2.4/ref": "@next/swc-linux-arm64-musl",
            },
            "@aspect_rules_js//platforms/pnpm:linux_x64": {
                ":.aspect_rules_js/node_modules/@next+swc-linux-x64-gnu@15.2.4/ref": "@next/swc-linux-x64-gnu",
                ":.aspect_rules_js/node_modules/@next+swc-linux-x64-musl@15.2.4/ref": "@next/swc-linux-x64-musl",
            },
            "@aspect_rules_js//platforms/pnpm:win32_arm64": {
                ":.aspect_rules_js/node_modules/@next+swc-win32-arm64-msvc@15.2.4/ref": "@next/swc-win32-arm64-msvc",
            },
            "@aspect_rules_js//platforms/pnpm:win32_x64": {
                ":.aspect_rules_js/node_modules/@next+swc-win32-x64-msvc@15.2.4/ref": "@next/swc-win32-x64-msvc",
            },
            "//conditions:default": {},
        }),
        lc_deps = {},
        has_lifecycle_build_target = False,
        has_transitive_closure = True,
        npm_package_target = "@@_main~npm~npm__next__15.2.4_1790925128//:pkg",
        package_store_name = _PACKAGE_STORE_NAME,
        lifecycle_hooks_env = {},
        lifecycle_hooks_execution_requirements = {},
        use_default_shell_env = False,
        exclude_package_contents = [],
    )

# Generated npm_link_imported_package_store_internal() for npm package next@15.2.4(@babel/core@7.28.5)(react-dom@19.2.0(react@19.2.0))(react@19.2.0)
# buildifier: disable=function-docstring
def npm_link_imported_package_store_internal(link_name = PACKAGE, dev = False):
    _npm_link_imported_package_store_internal(
        link_name,
        dev,
        root_package = _ROOT_PACKAGE,
        link_visibility = ["//visibility:public"],
        bins = {},
        package_store_name = _PACKAGE_STORE_NAME,
    )

# Generated public npm_package_store() and npm_link_package_store() targets for npm package next@15.2.4(@babel/core@7.28.5)(react-dom@19.2.0(react@19.2.0))(react@19.2.0)
# buildifier: disable=function-docstring
def npm_link_imported_package(
        name = "node_modules",
        dev = False,
        link = True):
    return _npm_link_imported_package_internal(
        name,
        package = PACKAGE,
        version = VERSION,
        dev = dev,
        root_package = _ROOT_PACKAGE,
        link = link,
        public_visibility = True,
        npm_link_imported_package_store_macro = npm_link_imported_package_store_internal,
        npm_imported_package_store_macro = npm_imported_package_store_internal,
    )
