"@generated by @aspect_rules_js//npm/private:npm_import.bzl for npm package rollup@4.55.2"

load("@aspect_rules_js//npm/private:npm_import.bzl", "bin_binary_internal", "bin_internal", "bin_test_internal")

_store_target = Label("@@//:.aspect_rules_js/node_modules/rollup@4.55.2")
_store_target_dir = Label("@@//:.aspect_rules_js/node_modules/rollup@4.55.2/dir")

def rollup(name, **kwargs):
    bin_internal(
        name,
        store_target = _store_target,
        store_target_dir = _store_target_dir,
        bin_path = "dist/bin/rollup",
        bin_mnemonic = "Rollup",
        **kwargs,
    )

def rollup_test(name, **kwargs):
    bin_test_internal(
        name,
        store_target = _store_target,
        store_target_dir = _store_target_dir,
        bin_path = "dist/bin/rollup",
        **kwargs,
    )

def rollup_binary(name, **kwargs):
    bin_binary_internal(
        name,
        store_target = _store_target,
        store_target_dir = _store_target_dir,
        bin_path = "dist/bin/rollup",
        **kwargs,
    )

bin = struct(
    rollup = rollup,
    rollup_test = rollup_test,
    rollup_binary = rollup_binary,
    rollup_path = "dist/bin/rollup",
)
