"@generated by @aspect_rules_js//npm/private:npm_import.bzl for npm package unused@0.2.2"

# buildifier: disable=bzl-visibility
load(
    "@aspect_rules_js//npm/private:npm_import.bzl",
    _npm_link_imported_package_internal = "npm_link_imported_package_internal",
    _npm_link_imported_package_store_internal = "npm_link_imported_package_store_internal",
)

# buildifier: disable=bzl-visibility
load("@aspect_rules_js//npm/private:npm_import.bzl", _npm_imported_simple_package_store_internal = "npm_imported_simple_package_store_internal")

PACKAGE = "unused"
VERSION = "0.2.2"
_ROOT_PACKAGE = ""
_KEY = "unused@0.2.2"
_PACKAGE_STORE_NAME = "unused@0.2.2"

# Generated npm_imported_package_store_internal() wrapper target for npm package unused@0.2.2
# buildifier: disable=function-docstring
def npm_imported_package_store_internal():
    _npm_imported_simple_package_store_internal(
        key = _KEY,
        package = PACKAGE,
        version = VERSION,
        deps = {
            ":.aspect_rules_js/node_modules/esprima@1.0.0": "esprima",
            ":.aspect_rules_js/node_modules/optimist@0.6.0": "optimist",
        },
        ref_deps = {
            ":.aspect_rules_js/node_modules/esprima@1.0.0/ref": "esprima",
            ":.aspect_rules_js/node_modules/optimist@0.6.0/ref": "optimist",
        },
        npm_package_target = "@@_main~npm~npm__unused__0.2.2//:pkg",
        package_store_name = _PACKAGE_STORE_NAME,
        exclude_package_contents = [],
    )

# Generated npm_link_imported_package_store_internal() for npm package unused@0.2.2
# buildifier: disable=function-docstring
def npm_link_imported_package_store_internal(link_name = PACKAGE, dev = False):
    _npm_link_imported_package_store_internal(
        link_name,
        dev,
        root_package = _ROOT_PACKAGE,
        link_visibility = ["//npm/private/test:__subpackages__"],
        bins = {},
        package_store_name = _PACKAGE_STORE_NAME,
    )

# Generated public npm_package_store() and npm_link_package_store() targets for npm package unused@0.2.2
# buildifier: disable=function-docstring
def npm_link_imported_package(
        name = "node_modules",
        dev = False,
        link = True):
    return _npm_link_imported_package_internal(
        name,
        package = PACKAGE,
        version = VERSION,
        dev = dev,
        root_package = _ROOT_PACKAGE,
        link = link,
        public_visibility = False,
        npm_link_imported_package_store_macro = npm_link_imported_package_store_internal,
        npm_imported_package_store_macro = npm_imported_package_store_internal,
    )
