packages:
    - 'examples/js_binary'
    - 'examples/macro'
    - 'examples/npm_deps'
    - 'examples/npm_package/libs/lib_a'
    - 'examples/npm_package/packages/pkg_a'
    - 'examples/npm_package/packages/pkg_b'
    - 'examples/npm_package/packages/pkg_d'
    - 'examples/webpack_cli'
    - 'examples/linked_empty_node_modules'
    - 'js/private/coverage/bundle'
    - 'js/private/worker/src'
    - 'js/private/image'
    - 'js/private/test/image'
    - 'js/private/test/js_run_devserver'
    - 'npm/private/test'
    - 'npm/private/test/npm_package'
