packages:
    - 'examples/*'
    - 'examples/js_lib_pkg/*'
    - 'examples/npm_package/libs/*'
    - 'examples/npm_package/packages/*'
    - 'js/private/coverage/bundle'
    - 'js/private/devserver/src'
    - 'js/private/worker/src'
    - 'js/private/test/*'
    - 'npm/private/test'
    - 'npm/private/test/*'
