packages:
    - 'examples/*'
    - 'examples/npm_package/libs/*'
    - 'examples/npm_package/packages/*'
    - 'js/private/coverage/bundle'
    - 'js/private/worker/src'
    - 'js/private/image'
    - 'js/private/test/image'
    - 'js/private/test/js_run_devserver'
    - 'npm/private/test'
    - 'npm/private/test/npm_package'
