"@generated by @aspect_rules_js//npm/private:npm_import.bzl for npm package @aspect-test/c@2.0.0"

# buildifier: disable=bzl-visibility
load(
    "@aspect_rules_js//npm/private:npm_import.bzl",
    _npm_imported_package_store_internal = "npm_imported_package_store_internal",
    _npm_link_imported_package_internal = "npm_link_imported_package_internal",
    _npm_link_imported_package_store_internal = "npm_link_imported_package_store_internal",
)

PACKAGE = "@aspect-test/c"
VERSION = "2.0.0"
_ROOT_PACKAGE = "<LOCKVERSION>"
_KEY = "@aspect-test/c@2.0.0"
_PACKAGE_STORE_NAME = "@aspect-test+c@2.0.0"

# Generated npm_imported_package_store_internal() wrapper target for npm package @aspect-test/c@2.0.0
# buildifier: disable=function-docstring
def npm_imported_package_store_internal():
    _npm_imported_package_store_internal(
        key = _KEY,
        package = PACKAGE,
        version = VERSION,
        root_package = _ROOT_PACKAGE,
        deps = {
            ":.aspect_rules_js/node_modules/@aspect-test+c@2.0.0/pkg": "@aspect-test/c",
        },
        ref_deps = {},
        lc_deps = {
            ":.aspect_rules_js/node_modules/@aspect-test+c@2.0.0/pkg_pre_lc_lite": "@aspect-test/c",
        },
        has_lifecycle_build_target = True,
        has_transitive_closure = False,
        npm_package_target = "@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_aspect-test_c__2.0.0//:pkg",
        package_store_name = _PACKAGE_STORE_NAME,
        lifecycle_hooks_env = {},
        lifecycle_hooks_execution_requirements = {
            "no-sandbox": "1",
        },
        use_default_shell_env = False,
        exclude_package_contents = [],
        exclude_package_contents_presets = ["basic"],
    )

# Generated npm_link_imported_package_store_internal() for npm package @aspect-test/c@2.0.0
# buildifier: disable=function-docstring
def npm_link_imported_package_store_internal(link_name = PACKAGE, dev = False):
    _npm_link_imported_package_store_internal(
        link_name,
        dev,
        root_package = _ROOT_PACKAGE,
        link_visibility = ["//visibility:public"],
        bins = {},
        package_store_name = _PACKAGE_STORE_NAME,
    )

# Generated public npm_package_store() and npm_link_package_store() targets for npm package @aspect-test/c@2.0.0
# buildifier: disable=function-docstring
def npm_link_imported_package(
        name = "node_modules",
        dev = False,
        link = True):
    return _npm_link_imported_package_internal(
        name,
        package = PACKAGE,
        version = VERSION,
        dev = dev,
        root_package = _ROOT_PACKAGE,
        link = link,
        public_visibility = True,
        npm_link_imported_package_store_macro = npm_link_imported_package_store_internal,
        npm_imported_package_store_macro = npm_imported_package_store_internal,
    )
