"""@generated by npm_translate_lock(name = "npm", pnpm_lock = "@//:pnpm-lock.yaml")"""

load("@aspect_rules_js//npm:repositories.bzl", "npm_import")

# Generated npm_import repository rules corresponding to npm packages in @//:pnpm-lock.yaml
# buildifier: disable=function-docstring
def npm_repositories():
    npm_import(
        name = "npm__at_aspect-test_c__2.0.0",
        root_package = "",
        link_workspace = "",
        link_packages = {
            "": ["@aspect-test/c"],
        },
        package = "@aspect-test/c",
        version = "2.0.0",
        url = "https://registry.npmjs.org/@aspect-test/c/-/c-2.0.0.tgz",
        package_visibility = ["//visibility:public"],
        integrity = "sha512-vRuHi/8zxZ+IRGdgdX4VoMNFZrR9UqO87yQx61IGIkjgV7QcKUeu5jfvIE3Mr0WNQeMdO1JpyTx1UUpsE73iug==",
        transitive_closure = {
            "@aspect-test/c": ["2.0.0"],
        },
    )
