local_repository(
    name = "aspect_rules_js",
    path = "../..",
)

local_repository(
    name = "local_repo",
    path = "./local_repo",
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")

rules_js_dependencies()

load("@aspect_rules_js//js:toolchains.bzl", "rules_js_register_toolchains")

rules_js_register_toolchains()

load("@aspect_rules_js//npm:repositories.bzl", "npm_translate_lock")

npm_translate_lock(
    name = "npm",
    data = [
        "//:package.json",
        "//:pnpm-workspace.yaml",
    ],
    npmrc = "//:.npmrc",
    patch_args = {
        "meaning-of-life": ["-p1"],
    },
    patches = {
        "meaning-of-life@1.0.0": ["@local_repo//:meaning-of-life@1.0.0.patch"],
    },
    pnpm_lock = "//:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
)

load("@npm//:repositories.bzl", "npm_repositories")

npm_repositories()
