local_repository(
    name = "aspect_rules_js",
    path = "../..",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "package_metadata",
    sha256 = "7446b71263039c7a5e90c4a069fd4c090e12a1a6c69a20eb4cd76034d610beb6",
    strip_prefix = "supply-chain-0.0.1/metadata",
    url = "https://github.com/bazel-contrib/supply-chain/releases/download/v0.0.1/supply-chain-v0.0.1.tar.gz",
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")

rules_js_dependencies()

load("@aspect_rules_js//js:toolchains.bzl", "DEFAULT_NODE_VERSION", "rules_js_register_toolchains")

rules_js_register_toolchains(node_version = DEFAULT_NODE_VERSION)
