"""@generated by npm_translate_lock(name = "lock-<LOCKVERSION>", pnpm_lock = "@@//<LOCKVERSION>:pnpm-lock.yaml")"""

load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__ansi-regex__5.0.1__links//:defs.bzl", store_0 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__ansi-regex__6.1.0__links//:defs.bzl", store_1 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__ansi-styles__4.3.0__links//:defs.bzl", store_2 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__ansi-styles__6.2.1__links//:defs.bzl", store_3 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_aspect-test_a__5.0.2__links//:defs.bzl", link_4 = "npm_link_imported_package_store", store_4 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_aspect-test_b__5.0.2__links//:defs.bzl", link_5 = "npm_link_imported_package_store", store_5 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_aspect-test_c__2.0.0__links//:defs.bzl", link_6 = "npm_link_imported_package_store", store_6 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_aspect-test_c__2.0.1__links//:defs.bzl", link_7 = "npm_link_imported_package_store", store_7 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_aspect-test_c__2.0.2__links//:defs.bzl", store_8 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_aspect-test_d__2.0.0_at_aspect-test_c_2.0.0__links//:defs.bzl", link_9 = "npm_link_imported_package_store", store_9 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_aspect-test_d__2.0.0_at_aspect-test_c_2.0.1__links//:defs.bzl", link_10 = "npm_link_imported_package_store", store_10 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_aspect-test_d__2.0.0_at_aspect-test_c_2.0.2__links//:defs.bzl", store_11 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_aspect-test_e__1.0.0__links//:defs.bzl", link_12 = "npm_link_imported_package_store", store_12 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_aspect-test_h__1.0.0__links//:defs.bzl", link_13 = "npm_link_imported_package_store", store_13 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_foo_jsonify__at_github.com_aspect-build_test-packages_releases_download_0.0.0_at_foo-jsonify-0.0.0.tgz__links//:defs.bzl", link_14 = "npm_link_imported_package_store", store_14 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_isaacs_cliui__8.0.2__links//:defs.bzl", link_15 = "npm_link_imported_package_store", store_15 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_rollup_plugin-typescript__8.2.1_1813138439__links//:defs.bzl", link_16 = "npm_link_imported_package_store", store_16 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_rollup_pluginutils__3.1.0_rollup_3.29.4__links//:defs.bzl", store_17 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_types_archiver__5.3.1__links//:defs.bzl", link_18 = "npm_link_imported_package_store", store_18 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_types_estree__0.0.39__links//:defs.bzl", store_19 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_types_glob__8.1.0__links//:defs.bzl", store_20 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_types_minimatch__5.1.2__links//:defs.bzl", store_21 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_types_node__16.18.11__links//:defs.bzl", link_22 = "npm_link_imported_package_store", store_22 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__at_types_sizzle__2.3.9__links//:defs.bzl", link_23 = "npm_link_imported_package_store", store_23 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__color-convert__2.0.1__links//:defs.bzl", store_24 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__color-name__1.1.4__links//:defs.bzl", store_25 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__debug__github.com_ngokevin_debug_9742c5f383a6f8046241920156236ade8ec30d53__links//:defs.bzl", link_26 = "npm_link_imported_package_store", store_26 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__dequal__2.0.3__links//:defs.bzl", store_27 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__diff__at_github.com_kpdecker_jsdiff_archive_refs_tags_v5.2.0.tar.gz__links//:defs.bzl", store_28 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__eastasianwidth__0.2.0__links//:defs.bzl", store_29 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__emoji-regex__8.0.0__links//:defs.bzl", store_30 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__emoji-regex__9.2.2__links//:defs.bzl", store_31 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__estree-walker__1.0.1__links//:defs.bzl", store_32 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__fsevents__2.3.3__links//:defs.bzl", store_33 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__function-bind__1.1.2__links//:defs.bzl", store_34 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__hasown__2.0.2__links//:defs.bzl", store_35 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__hello__at_gitpkg.vercel.app_EqualMa_gitpkg-hello_packages_hello__links//:defs.bzl", link_36 = "npm_link_imported_package_store", store_36 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__is-core-module__2.16.1__links//:defs.bzl", store_37 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__is-fullwidth-code-point__3.0.0__links//:defs.bzl", store_38 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__is-odd__0.1.0__links//:defs.bzl", link_39 = "npm_link_imported_package_store", store_39 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__is-odd__1.0.0__links//:defs.bzl", link_40 = "npm_link_imported_package_store", store_40 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__is-odd__2.0.0__links//:defs.bzl", link_41 = "npm_link_imported_package_store", store_41 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__is-odd__3.0.0__links//:defs.bzl", link_42 = "npm_link_imported_package_store", store_42 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__is-odd__3.0.1__links//:defs.bzl", link_43 = "npm_link_imported_package_store", store_43 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__jquery__github.com_jquery_jquery_399b201bb3143a3952894cf3489b4848fc003967__links//:defs.bzl", link_44 = "npm_link_imported_package_store", store_44 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__jquery__github.com_jquery_jquery_e61fccb9d736235b4b011f89cba6866bc0b8997d__links//:defs.bzl", link_45 = "npm_link_imported_package_store", store_45 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__kleur__4.1.5__links//:defs.bzl", store_46 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__lodash__4.17.21__links//:defs.bzl", link_47 = "npm_link_imported_package_store", store_47 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__meaning-of-life__1.0.0_o3deharooos255qt5xdujc3cuq__links//:defs.bzl", link_48 = "npm_link_imported_package_store", store_48 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__mri__1.2.0__links//:defs.bzl", store_49 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__ms__0.7.3__links//:defs.bzl", store_50 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__path-parse__1.0.7__links//:defs.bzl", store_51 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__picomatch__2.3.1__links//:defs.bzl", store_52 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__resolve__1.22.10__links//:defs.bzl", store_53 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__rollup__2.14.0__links//:defs.bzl", link_54 = "npm_link_imported_package_store", store_54 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__rollup__3.29.4__links//:defs.bzl", link_55 = "npm_link_imported_package_store", store_55 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__sade__1.8.1__links//:defs.bzl", store_56 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__string-width__4.2.3__links//:defs.bzl", store_57 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__string-width__5.1.2__links//:defs.bzl", store_58 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__strip-ansi__6.0.1__links//:defs.bzl", store_59 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__strip-ansi__7.1.0__links//:defs.bzl", store_60 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__supports-preserve-symlinks-flag__1.0.0__links//:defs.bzl", store_61 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__tslib__2.6.3__links//:defs.bzl", link_62 = "npm_link_imported_package_store", store_62 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__typescript__5.5.2__links//:defs.bzl", link_63 = "npm_link_imported_package_store", store_63 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__uvu__0.5.6__links//:defs.bzl", link_64 = "npm_link_imported_package_store", store_64 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__wrap-ansi__7.0.0__links//:defs.bzl", store_65 = "npm_imported_package_store")
load("@@aspect_rules_js~~npm~lock-<LOCKVERSION>__wrap-ansi__8.1.0__links//:defs.bzl", store_66 = "npm_imported_package_store")

# buildifier: disable=bzl-visibility
load("@aspect_rules_js//js:defs.bzl", _js_library = "js_library")

# buildifier: disable=bzl-visibility
load("@aspect_rules_js//npm/private:npm_link_package_store.bzl", _npm_link_package_store = "npm_link_package_store")

# buildifier: disable=bzl-visibility
load("@aspect_rules_js//npm/private:npm_package_store.bzl", _npm_package_store = "npm_package_store", _npm_local_package_store = "npm_local_package_store_internal")

_LINK_PACKAGES = ["<LOCKVERSION>", "projects/a", "projects/a-types", "projects/b", "projects/c", "projects/d", "projects/peer-types", "projects/peers-combo-1", "projects/peers-combo-2", "vendored/is-number"]

# buildifier: disable=function-docstring
def npm_link_all_packages(imported_links = []):
    bazel_package = native.package_name()
    root_package = "<LOCKVERSION>"
    is_root = bazel_package == root_package
    link = bazel_package in _LINK_PACKAGES
    if not is_root and not link:
        msg = "The npm_link_all_packages() macro loaded from @aspect_rules_js~~npm~lock-<LOCKVERSION>//:defs.bzl and called in bazel package '%s' may only be called in bazel packages that correspond to the pnpm root package or pnpm workspace projects. Projects are discovered from the pnpm-lock.yaml and may be missing if the lockfile is out of date. Root package: '<LOCKVERSION>', pnpm workspace projects: %s" % (bazel_package, "'" + "', '".join(_LINK_PACKAGES) + "'")
        fail(msg)
    link_targets = []
    scope_targets = {}

    for link_fn in imported_links:
        new_link_targets, new_scope_targets = link_fn()
        link_targets.extend(new_link_targets)
        for _scope, _targets in new_scope_targets.items():
            if _scope not in scope_targets:
                scope_targets[_scope] = []
            scope_targets[_scope].extend(_targets)

    if is_root:
        store_0()
        store_1()
        store_2()
        store_3()
        store_4()
        store_5()
        store_6()
        store_7()
        store_8()
        store_9()
        store_10()
        store_11()
        store_12()
        store_13()
        store_14()
        store_15()
        store_16()
        store_17()
        store_18()
        store_19()
        store_20()
        store_21()
        store_22()
        store_23()
        store_24()
        store_25()
        store_26()
        store_27()
        store_28()
        store_29()
        store_30()
        store_31()
        store_32()
        store_33()
        store_34()
        store_35()
        store_36()
        store_37()
        store_38()
        store_39()
        store_40()
        store_41()
        store_42()
        store_43()
        store_44()
        store_45()
        store_46()
        store_47()
        store_48()
        store_49()
        store_50()
        store_51()
        store_52()
        store_53()
        store_54()
        store_55()
        store_56()
        store_57()
        store_58()
        store_59()
        store_60()
        store_61()
        store_62()
        store_63()
        store_64()
        store_65()
        store_66()
    if link:
        if bazel_package == "<LOCKVERSION>":
            link_4("@aspect-test-a-bad-scope")
            link_targets.append(":node_modules/@aspect-test-a-bad-scope")
            if "@aspect-test-a-bad-scop" not in scope_targets:
                scope_targets["@aspect-test-a-bad-scop"] = [link_targets[-1]]
            else:
                scope_targets["@aspect-test-a-bad-scop"].append(link_targets[-1])
            link_4("@aspect-test-custom-scope/a")
            link_targets.append(":node_modules/@aspect-test-custom-scope/a")
            if "@aspect-test-custom-scope" not in scope_targets:
                scope_targets["@aspect-test-custom-scope"] = [link_targets[-1]]
            else:
                scope_targets["@aspect-test-custom-scope"].append(link_targets[-1])
            link_4("@aspect-test/a")
            link_targets.append(":node_modules/@aspect-test/a")
            if "@aspect-test" not in scope_targets:
                scope_targets["@aspect-test"] = [link_targets[-1]]
            else:
                scope_targets["@aspect-test"].append(link_targets[-1])
            link_4("@aspect-test/a2")
            link_targets.append(":node_modules/@aspect-test/a2")
            if "@aspect-test" not in scope_targets:
                scope_targets["@aspect-test"] = [link_targets[-1]]
            else:
                scope_targets["@aspect-test"].append(link_targets[-1])
            link_4("aspect-test-a-no-scope")
            link_targets.append(":node_modules/aspect-test-a-no-scope")
            link_4("aspect-test-a/no-at")
            link_targets.append(":node_modules/aspect-test-a/no-at")
            link_5("@aspect-test/b")
            link_targets.append(":node_modules/@aspect-test/b")
            if "@aspect-test" not in scope_targets:
                scope_targets["@aspect-test"] = [link_targets[-1]]
            else:
                scope_targets["@aspect-test"].append(link_targets[-1])
            link_6("@aspect-test/c")
            link_targets.append(":node_modules/@aspect-test/c")
            if "@aspect-test" not in scope_targets:
                scope_targets["@aspect-test"] = [link_targets[-1]]
            else:
                scope_targets["@aspect-test"].append(link_targets[-1])
            link_12("@aspect-test/e")
            link_targets.append(":node_modules/@aspect-test/e")
            if "@aspect-test" not in scope_targets:
                scope_targets["@aspect-test"] = [link_targets[-1]]
            else:
                scope_targets["@aspect-test"].append(link_targets[-1])
            link_13("@aspect-test/h-is-only-optional")
            link_targets.append(":node_modules/@aspect-test/h-is-only-optional")
            if "@aspect-test" not in scope_targets:
                scope_targets["@aspect-test"] = [link_targets[-1]]
            else:
                scope_targets["@aspect-test"].append(link_targets[-1])
            link_14("jsonify")
            link_targets.append(":node_modules/jsonify")
            link_15("@isaacs/cliui")
            link_targets.append(":node_modules/@isaacs/cliui")
            if "@isaacs" not in scope_targets:
                scope_targets["@isaacs"] = [link_targets[-1]]
            else:
                scope_targets["@isaacs"].append(link_targets[-1])
            link_16("rollup-plugin-with-peers")
            link_targets.append(":node_modules/rollup-plugin-with-peers")
            link_18("@types/archiver")
            link_targets.append(":node_modules/@types/archiver")
            if "@types" not in scope_targets:
                scope_targets["@types"] = [link_targets[-1]]
            else:
                scope_targets["@types"].append(link_targets[-1])
            link_22("@types/node")
            link_targets.append(":node_modules/@types/node")
            if "@types" not in scope_targets:
                scope_targets["@types"] = [link_targets[-1]]
            else:
                scope_targets["@types"].append(link_targets[-1])
            link_22("alias-types-node")
            link_targets.append(":node_modules/alias-types-node")
            link_23("alias-only-sizzle")
            link_targets.append(":node_modules/alias-only-sizzle")
            link_26("debug")
            link_targets.append(":node_modules/debug")
            link_36("hello")
            link_targets.append(":node_modules/hello")
            link_39("is-odd-v0")
            link_targets.append(":node_modules/is-odd-v0")
            link_40("is-odd-v1")
            link_targets.append(":node_modules/is-odd-v1")
            link_41("is-odd-v2")
            link_targets.append(":node_modules/is-odd-v2")
            link_42("is-odd-v3")
            link_targets.append(":node_modules/is-odd-v3")
            link_43("is-odd")
            link_targets.append(":node_modules/is-odd")
            link_43("is-odd-alias")
            link_targets.append(":node_modules/is-odd-alias")
            link_44("jquery-git-ssh-399b201")
            link_targets.append(":node_modules/jquery-git-ssh-399b201")
            link_45("jquery-git-ssh-e61fccb")
            link_targets.append(":node_modules/jquery-git-ssh-e61fccb")
            link_47("lodash")
            link_targets.append(":node_modules/lodash")
            link_48("meaning-of-life")
            link_targets.append(":node_modules/meaning-of-life")
            link_54("rollup")
            link_targets.append(":node_modules/rollup")
            link_55("rollup3")
            link_targets.append(":node_modules/rollup3")
            link_62("tslib")
            link_targets.append(":node_modules/tslib")
            link_63("typescript")
            link_targets.append(":node_modules/typescript")
            link_64("uvu")
            link_targets.append(":node_modules/uvu")
        elif bazel_package == "projects/peers-combo-2":
            link_6("@aspect-test/c")
            link_targets.append(":node_modules/@aspect-test/c")
            if "@aspect-test" not in scope_targets:
                scope_targets["@aspect-test"] = [link_targets[-1]]
            else:
                scope_targets["@aspect-test"].append(link_targets[-1])
            link_9("@aspect-test/d")
            link_targets.append(":node_modules/@aspect-test/d")
            if "@aspect-test" not in scope_targets:
                scope_targets["@aspect-test"] = [link_targets[-1]]
            else:
                scope_targets["@aspect-test"].append(link_targets[-1])
        elif bazel_package == "projects/peers-combo-1":
            link_7("@aspect-test/c")
            link_targets.append(":node_modules/@aspect-test/c")
            if "@aspect-test" not in scope_targets:
                scope_targets["@aspect-test"] = [link_targets[-1]]
            else:
                scope_targets["@aspect-test"].append(link_targets[-1])
            link_10("@aspect-test/d")
            link_targets.append(":node_modules/@aspect-test/d")
            if "@aspect-test" not in scope_targets:
                scope_targets["@aspect-test"] = [link_targets[-1]]
            else:
                scope_targets["@aspect-test"].append(link_targets[-1])
        elif bazel_package == "projects/peer-types":
            link_14("jsonify")
            link_targets.append(":node_modules/jsonify")
            link_36("hello")
            link_targets.append(":node_modules/hello")
        elif bazel_package == "projects/a-types":
            link_22("@types/node")
            link_targets.append(":node_modules/@types/node")
            if "@types" not in scope_targets:
                scope_targets["@types"] = [link_targets[-1]]
            else:
                scope_targets["@types"].append(link_targets[-1])
        elif bazel_package == "projects/b":
            link_22("@types/node")
            link_targets.append(":node_modules/@types/node")
            if "@types" not in scope_targets:
                scope_targets["@types"] = [link_targets[-1]]
            else:
                scope_targets["@types"].append(link_targets[-1])

    if is_root:
        _npm_local_package_store(
            package_store_name = "@scoped+c@0.0.0",
            src = "//projects/c:pkg",
            package = "@scoped/c",
            version = "0.0.0",
            deps = {
                "//<LOCKVERSION>:.aspect_rules_js/@scoped+a@0.0.0": "@scoped/a",
                "//<LOCKVERSION>:.aspect_rules_js/@scoped+b@0.0.0": "@scoped/b",
            },
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

    if bazel_package in ["<LOCKVERSION>", "projects/peer-types"]:
        # terminal target for direct dependencies
        _npm_link_package_store(
            name = "node_modules/@scoped/c",
            src = "//<LOCKVERSION>:.aspect_rules_js/@scoped+c@0.0.0",
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

        # filegroup target that provides a single file which is
        # package directory for use in $(execpath) and $(rootpath)
        native.filegroup(
            name = "node_modules/@scoped/c/dir",
            srcs = [":node_modules/@scoped/c"],
            output_group = "package_directory",
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )
        link_targets.append(":node_modules/@scoped/c")
        if "@scoped" not in scope_targets:
            scope_targets["@scoped"] = [link_targets[-1]]
        else:
            scope_targets["@scoped"].append(link_targets[-1])

    if is_root:
        _npm_local_package_store(
            package_store_name = "is-number@0.0.0",
            src = "//vendored/is-number:pkg",
            package = "is-number",
            version = "0.0.0",
            deps = {},
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

    if is_root:
        _npm_local_package_store(
            package_store_name = "@scoped+a@0.0.0",
            src = "//projects/a:pkg",
            package = "@scoped/a",
            version = "0.0.0",
            deps = {},
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

    if bazel_package in ["<LOCKVERSION>", "projects/b", "projects/c", "projects/d", "projects/peer-types"]:
        # terminal target for direct dependencies
        _npm_link_package_store(
            name = "node_modules/@scoped/a",
            src = "//<LOCKVERSION>:.aspect_rules_js/@scoped+a@0.0.0",
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

        # filegroup target that provides a single file which is
        # package directory for use in $(execpath) and $(rootpath)
        native.filegroup(
            name = "node_modules/@scoped/a/dir",
            srcs = [":node_modules/@scoped/a"],
            output_group = "package_directory",
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )
        link_targets.append(":node_modules/@scoped/a")
        if "@scoped" not in scope_targets:
            scope_targets["@scoped"] = [link_targets[-1]]
        else:
            scope_targets["@scoped"].append(link_targets[-1])

    if is_root:
        _npm_local_package_store(
            package_store_name = "@scoped+b@0.0.0",
            src = "//projects/b:pkg",
            package = "@scoped/b",
            version = "0.0.0",
            deps = {
                "//<LOCKVERSION>:.aspect_rules_js/@scoped+a@0.0.0": "@scoped/a",
            },
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

    if bazel_package in ["<LOCKVERSION>", "projects/c", "projects/d", "projects/peer-types"]:
        # terminal target for direct dependencies
        _npm_link_package_store(
            name = "node_modules/@scoped/b",
            src = "//<LOCKVERSION>:.aspect_rules_js/@scoped+b@0.0.0",
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

        # filegroup target that provides a single file which is
        # package directory for use in $(execpath) and $(rootpath)
        native.filegroup(
            name = "node_modules/@scoped/b/dir",
            srcs = [":node_modules/@scoped/b"],
            output_group = "package_directory",
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )
        link_targets.append(":node_modules/@scoped/b")
        if "@scoped" not in scope_targets:
            scope_targets["@scoped"] = [link_targets[-1]]
        else:
            scope_targets["@scoped"].append(link_targets[-1])

    if is_root:
        _npm_local_package_store(
            package_store_name = "@scoped+d@0.0.0",
            src = "//projects/d:pkg",
            package = "@scoped/d",
            version = "0.0.0",
            deps = {
                "//<LOCKVERSION>:.aspect_rules_js/@scoped+a@0.0.0": "@scoped/a",
                "//<LOCKVERSION>:.aspect_rules_js/@scoped+b@0.0.0": "@scoped/b",
            },
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

    if bazel_package in ["<LOCKVERSION>"]:
        # terminal target for direct dependencies
        _npm_link_package_store(
            name = "node_modules/@scoped/d",
            src = "//<LOCKVERSION>:.aspect_rules_js/@scoped+d@0.0.0",
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

        # filegroup target that provides a single file which is
        # package directory for use in $(execpath) and $(rootpath)
        native.filegroup(
            name = "node_modules/@scoped/d/dir",
            srcs = [":node_modules/@scoped/d"],
            output_group = "package_directory",
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )
        link_targets.append(":node_modules/@scoped/d")
        if "@scoped" not in scope_targets:
            scope_targets["@scoped"] = [link_targets[-1]]
        else:
            scope_targets["@scoped"].append(link_targets[-1])

    if is_root:
        _npm_local_package_store(
            package_store_name = "alias-project-a@0.0.0",
            src = "//projects/a:pkg",
            package = "alias-project-a",
            version = "0.0.0",
            deps = {},
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

    if bazel_package in ["<LOCKVERSION>"]:
        # terminal target for direct dependencies
        _npm_link_package_store(
            name = "node_modules/alias-project-a",
            src = "//<LOCKVERSION>:.aspect_rules_js/alias-project-a@0.0.0",
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

        # filegroup target that provides a single file which is
        # package directory for use in $(execpath) and $(rootpath)
        native.filegroup(
            name = "node_modules/alias-project-a/dir",
            srcs = [":node_modules/alias-project-a"],
            output_group = "package_directory",
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )
        link_targets.append(":node_modules/alias-project-a")

    if is_root:
        _npm_local_package_store(
            package_store_name = "scoped+bad@0.0.0",
            src = "//projects/b:pkg",
            package = "scoped/bad",
            version = "0.0.0",
            deps = {
                "//<LOCKVERSION>:.aspect_rules_js/@scoped+a@0.0.0": "@scoped/a",
            },
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

    if bazel_package in ["<LOCKVERSION>"]:
        # terminal target for direct dependencies
        _npm_link_package_store(
            name = "node_modules/scoped/bad",
            src = "//<LOCKVERSION>:.aspect_rules_js/scoped+bad@0.0.0",
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

        # filegroup target that provides a single file which is
        # package directory for use in $(execpath) and $(rootpath)
        native.filegroup(
            name = "node_modules/scoped/bad/dir",
            srcs = [":node_modules/scoped/bad"],
            output_group = "package_directory",
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )
        link_targets.append(":node_modules/scoped/bad")

    if is_root:
        _npm_local_package_store(
            package_store_name = "test-c200-d200@0.0.0",
            src = "//projects/peers-combo-2:pkg",
            package = "test-c200-d200",
            version = "0.0.0",
            deps = {
                "//<LOCKVERSION>:.aspect_rules_js/@aspect-test+c@2.0.0": "@aspect-test/c",
                "//<LOCKVERSION>:.aspect_rules_js/@aspect-test+d@2.0.0_at_aspect-test_c_2.0.0": "@aspect-test/d",
            },
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

    if bazel_package in ["<LOCKVERSION>"]:
        # terminal target for direct dependencies
        _npm_link_package_store(
            name = "node_modules/test-c200-d200",
            src = "//<LOCKVERSION>:.aspect_rules_js/test-c200-d200@0.0.0",
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

        # filegroup target that provides a single file which is
        # package directory for use in $(execpath) and $(rootpath)
        native.filegroup(
            name = "node_modules/test-c200-d200/dir",
            srcs = [":node_modules/test-c200-d200"],
            output_group = "package_directory",
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )
        link_targets.append(":node_modules/test-c200-d200")

    if is_root:
        _npm_local_package_store(
            package_store_name = "test-c201-d200@0.0.0",
            src = "//projects/peers-combo-1:pkg",
            package = "test-c201-d200",
            version = "0.0.0",
            deps = {
                "//<LOCKVERSION>:.aspect_rules_js/@aspect-test+c@2.0.1": "@aspect-test/c",
                "//<LOCKVERSION>:.aspect_rules_js/@aspect-test+d@2.0.0_at_aspect-test_c_2.0.1": "@aspect-test/d",
            },
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

    if bazel_package in ["<LOCKVERSION>"]:
        # terminal target for direct dependencies
        _npm_link_package_store(
            name = "node_modules/test-c201-d200",
            src = "//<LOCKVERSION>:.aspect_rules_js/test-c201-d200@0.0.0",
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

        # filegroup target that provides a single file which is
        # package directory for use in $(execpath) and $(rootpath)
        native.filegroup(
            name = "node_modules/test-c201-d200/dir",
            srcs = [":node_modules/test-c201-d200"],
            output_group = "package_directory",
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )
        link_targets.append(":node_modules/test-c201-d200")

    if is_root:
        _npm_local_package_store(
            package_store_name = "test-peer-types@0.0.0",
            src = "//projects/peer-types:pkg",
            package = "test-peer-types",
            version = "0.0.0",
            deps = {},
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

    if bazel_package in ["<LOCKVERSION>"]:
        # terminal target for direct dependencies
        _npm_link_package_store(
            name = "node_modules/test-peer-types",
            src = "//<LOCKVERSION>:.aspect_rules_js/test-peer-types@0.0.0",
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

        # filegroup target that provides a single file which is
        # package directory for use in $(execpath) and $(rootpath)
        native.filegroup(
            name = "node_modules/test-peer-types/dir",
            srcs = [":node_modules/test-peer-types"],
            output_group = "package_directory",
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )
        link_targets.append(":node_modules/test-peer-types")

    if is_root:
        _npm_local_package_store(
            package_store_name = "a-types@0.0.0",
            src = "//projects/a-types:pkg",
            package = "a-types",
            version = "0.0.0",
            deps = {
                "//<LOCKVERSION>:.aspect_rules_js/@types+node@16.18.11": "@types/node",
            },
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

    if bazel_package in ["projects/b"]:
        # terminal target for direct dependencies
        _npm_link_package_store(
            name = "node_modules/a-types",
            src = "//<LOCKVERSION>:.aspect_rules_js/a-types@0.0.0",
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )

        # filegroup target that provides a single file which is
        # package directory for use in $(execpath) and $(rootpath)
        native.filegroup(
            name = "node_modules/a-types/dir",
            srcs = [":node_modules/a-types"],
            output_group = "package_directory",
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )
        link_targets.append(":node_modules/a-types")

    for scope, scoped_targets in scope_targets.items():
        _js_library(
            name = "node_modules/{}".format(scope),
            srcs = scoped_targets,
            tags = ["manual"],
            visibility = ["//visibility:public"],
        )

    _js_library(
        name = "node_modules",
        srcs = link_targets,
        tags = ["manual"],
        visibility = ["//visibility:public"],
    )

# buildifier: disable=function-docstring
def npm_link_targets(package = None):
    bazel_package = package if package != None else native.package_name()
    link = bazel_package in _LINK_PACKAGES

    link_targets = []

    if link:
        if bazel_package == "<LOCKVERSION>":
            link_targets.append(":node_modules/@aspect-test-a-bad-scope")
            link_targets.append(":node_modules/@aspect-test-custom-scope/a")
            link_targets.append(":node_modules/@aspect-test/a")
            link_targets.append(":node_modules/@aspect-test/a2")
            link_targets.append(":node_modules/aspect-test-a-no-scope")
            link_targets.append(":node_modules/aspect-test-a/no-at")
            link_targets.append(":node_modules/@aspect-test/b")
            link_targets.append(":node_modules/@aspect-test/c")
            link_targets.append(":node_modules/@aspect-test/e")
            link_targets.append(":node_modules/@aspect-test/h-is-only-optional")
            link_targets.append(":node_modules/jsonify")
            link_targets.append(":node_modules/@isaacs/cliui")
            link_targets.append(":node_modules/rollup-plugin-with-peers")
            link_targets.append(":node_modules/@types/archiver")
            link_targets.append(":node_modules/@types/node")
            link_targets.append(":node_modules/alias-types-node")
            link_targets.append(":node_modules/alias-only-sizzle")
            link_targets.append(":node_modules/debug")
            link_targets.append(":node_modules/hello")
            link_targets.append(":node_modules/is-odd-v0")
            link_targets.append(":node_modules/is-odd-v1")
            link_targets.append(":node_modules/is-odd-v2")
            link_targets.append(":node_modules/is-odd-v3")
            link_targets.append(":node_modules/is-odd")
            link_targets.append(":node_modules/is-odd-alias")
            link_targets.append(":node_modules/jquery-git-ssh-399b201")
            link_targets.append(":node_modules/jquery-git-ssh-e61fccb")
            link_targets.append(":node_modules/lodash")
            link_targets.append(":node_modules/meaning-of-life")
            link_targets.append(":node_modules/rollup")
            link_targets.append(":node_modules/rollup3")
            link_targets.append(":node_modules/tslib")
            link_targets.append(":node_modules/typescript")
            link_targets.append(":node_modules/uvu")
        elif bazel_package == "projects/peers-combo-2":
            link_targets.append(":node_modules/@aspect-test/c")
            link_targets.append(":node_modules/@aspect-test/d")
        elif bazel_package == "projects/peers-combo-1":
            link_targets.append(":node_modules/@aspect-test/c")
            link_targets.append(":node_modules/@aspect-test/d")
        elif bazel_package == "projects/peer-types":
            link_targets.append(":node_modules/jsonify")
            link_targets.append(":node_modules/hello")
        elif bazel_package == "projects/a-types":
            link_targets.append(":node_modules/@types/node")
        elif bazel_package == "projects/b":
            link_targets.append(":node_modules/@types/node")

    if bazel_package in ["<LOCKVERSION>", "projects/peer-types"]:
        link_targets.append(":node_modules/@scoped/c")

    if bazel_package in ["<LOCKVERSION>", "projects/b", "projects/c", "projects/d", "projects/peer-types"]:
        link_targets.append(":node_modules/@scoped/a")

    if bazel_package in ["<LOCKVERSION>", "projects/c", "projects/d", "projects/peer-types"]:
        link_targets.append(":node_modules/@scoped/b")

    if bazel_package in ["<LOCKVERSION>"]:
        link_targets.append(":node_modules/@scoped/d")

    if bazel_package in ["<LOCKVERSION>"]:
        link_targets.append(":node_modules/alias-project-a")

    if bazel_package in ["<LOCKVERSION>"]:
        link_targets.append(":node_modules/scoped/bad")

    if bazel_package in ["<LOCKVERSION>"]:
        link_targets.append(":node_modules/test-c200-d200")

    if bazel_package in ["<LOCKVERSION>"]:
        link_targets.append(":node_modules/test-c201-d200")

    if bazel_package in ["<LOCKVERSION>"]:
        link_targets.append(":node_modules/test-peer-types")

    if bazel_package in ["projects/b"]:
        link_targets.append(":node_modules/a-types")
    return link_targets
