local_repository(
    name = "aspect_rules_js",
    path = "../..",
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")

rules_js_dependencies()

load("@aspect_rules_js//js:toolchains.bzl", "DEFAULT_NODE_VERSION", "rules_js_register_toolchains")

rules_js_register_toolchains(node_version = DEFAULT_NODE_VERSION)

load("@aspect_rules_js//npm:repositories.bzl", "npm_translate_lock")

npm_translate_lock(
    name = "npm",
    data = [
        "//:package.json",
        "//:pnpm-workspace.yaml",
    ],
    npmrc = "//:.npmrc",
    patch_args = {
        "*": ["-p1"],
        "@gregmagolan/test-a": ["-p4"],
    },
    patches = {
        "@gregmagolan/test-a": ["//:patches/test-a.patch"],
        "@gregmagolan/test-a@0.0.1": ["//:patches/test-a@0.0.1.patch"],
        "@gregmagolan/test-b": ["//:patches/test-b.patch"],
    },
    pnpm_lock = "//:pnpm-lock.yaml",
    update_pnpm_lock = True,
    verify_node_modules_ignored = "//:.bazelignore",
    verify_patches = "//patches:patches.list",
)

load("@npm//:repositories.bzl", "npm_repositories")

npm_repositories()
