load("@npm_other_module_frontend//:defs.bzl", "npm_link_all_packages")
load("@npm_other_module_frontend//frontend:less/package_json.bzl", less_bin = "bin")

# npm packages linked in a sub-package of an external module, see
# https://github.com/aspect-build/rules_js/pull/2896
npm_link_all_packages()

less_bin.lessc_binary(
    name = "lessc",
    visibility = ["//visibility:public"],
)
