local_repository(
    name = "aspect_rules_js",
    path = "../..",
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")

rules_js_dependencies()

load("@rules_nodejs//nodejs:repositories.bzl", "DEFAULT_NODE_VERSION", "nodejs_register_toolchains")

nodejs_register_toolchains(
    name = "nodejs",
    node_version = DEFAULT_NODE_VERSION,
)

load("@aspect_rules_js//npm:repositories.bzl", "npm_translate_lock")

npm_translate_lock(
    name = "app1_npm",
    npmrc = "//:.npmrc",
    pnpm_lock = "//app1:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
)

load("@app1_npm//:repositories.bzl", app1_npm_repositories = "npm_repositories")

app1_npm_repositories()

npm_translate_lock(
    name = "app2_npm",
    npmrc = "//:.npmrc",
    pnpm_lock = "//app2:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
)

load("@app2_npm//:repositories.bzl", app2_npm_repositories = "npm_repositories")

app2_npm_repositories()
