load("@bazel_lib//lib:write_source_files.bzl", "write_source_files")
load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load(":merger.bzl", "coverage_merger")

exports_files([
    "coverage.sh.tpl",
    "coverage.js",
])

write_source_files(
    name = "coverage_checked",
    files = {
        "coverage.js": "//js/private/coverage/bundle:bundle.js",
    },
)

coverage_merger(
    name = "merger",
    visibility = ["//visibility:public"],
)

bzl_library(
    name = "extensions",
    srcs = ["extensions.bzl"],
    visibility = ["//js:__subpackages__"],
)
