workspace(name = "rules_foo")  # explicit name required for npm_translate_lock @rules_foo//foo:pnpm-lock.yaml" label in foo_repositories

local_repository(
    name = "aspect_rules_js",
    path = "../..",
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")

rules_js_dependencies()

load("@aspect_rules_js//js:toolchains.bzl", "rules_js_register_toolchains")

rules_js_register_toolchains(node_version = "16.14.2")

load("@rules_foo//foo:repositories.bzl", "foo_repositories")

foo_repositories()

load("@foo//:npm_repositories.bzl", foo_npm_repositories = "npm_repositories")

foo_npm_repositories()
