local_repository(
    name = "aspect_rules_js",
    path = "../..",
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")

rules_js_dependencies()

load("@aspect_rules_js//js:configure.bzl", "rules_js_register_toolchains")

rules_js_register_toolchains()

load("@aspect_rules_js//npm:repositories.bzl", "npm_translate_lock")

npm_translate_lock(
    name = "npm",
    data = [
        "//subdir:package.json",
        "//subdir:patches/debug@4.3.4.patch",
    ],
    patch_args = {
        "*": ["-p1"],
    },
    pnpm_lock = "//subdir:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
)

load("@npm//:repositories.bzl", "npm_repositories")

npm_repositories()
