/**
 * Verifies a checked-in Yarn PnP offline cache against yarn.lock.
 *
 * For every hard-linked package in .pnp.data.json, recomputes the sha512 of
 * the cache zip it resolves to and compares it with the checksum recorded in
 * yarn.lock. Also checks that the set of zips present under .yarn/cache is
 * exactly the set referenced by the resolution graph, so stale or foreign
 * archives cannot ride along unnoticed.
 *
 * Runs under Bazel via the pnp_verify_test macro generated by pnp_repository;
 * PNP_ROOT is the workspace-relative directory of the PnP project.
 */
import { createHash } from 'node:crypto'
import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

const root = process.env.PNP_ROOT || '.'
const errors = []

// Map physical locator -> checksum hash from yarn.lock. The lockfile is the
// restricted YAML subset Berry generates; entry keys are comma-separated
// descriptors and each block carries `resolution` and (for remote packages)
// `checksum` scalars.
const lockChecksums = new Map()
{
    const lock = readFileSync(join(root, 'yarn.lock'), 'utf8')
    let resolution = null
    for (const line of lock.split('\n')) {
        const resolutionMatch = line.match(/^ {2}resolution: "?([^"]+)"?$/)
        if (resolutionMatch) {
            resolution = resolutionMatch[1]
            continue
        }
        const checksumMatch = line.match(/^ {2}checksum: (?:[0-9a-z]+\/)?([0-9a-f]+)$/)
        if (checksumMatch && resolution) {
            lockChecksums.set(resolution, checksumMatch[1])
        }
        if (!line.startsWith(' ')) {
            resolution = null
        }
    }
}

const pnpData = JSON.parse(readFileSync(join(root, '.pnp.data.json'), 'utf8'))

const referencedZips = new Map() // zip filename -> physical locator
for (const [name, refs] of pnpData.packageRegistryData) {
    if (name === null) continue
    for (const [reference, info] of refs) {
        if (reference === null || info.linkType !== 'HARD') continue
        const match = info.packageLocation.match(/([^/]+\.zip)\/node_modules\//)
        if (!match) {
            errors.push(`${name}@${reference}: packageLocation ${info.packageLocation} does not point into the offline cache`)
            continue
        }
        const physicalReference = reference.startsWith('virtual:')
            ? reference.slice(reference.indexOf('#') + 1)
            : reference
        referencedZips.set(match[1], `${name}@${physicalReference}`)
    }
}

const presentZips = readdirSync(join(root, '.yarn/cache')).filter((f) => f.endsWith('.zip'))

for (const zip of presentZips) {
    if (!referencedZips.has(zip)) {
        errors.push(`${zip}: present in .yarn/cache but not referenced by .pnp.data.json`)
    }
}

for (const [zip, locator] of referencedZips) {
    if (!presentZips.includes(zip)) {
        errors.push(`${locator}: cache archive ${zip} is missing from .yarn/cache`)
        continue
    }
    const expected = lockChecksums.get(locator)
    if (!expected) {
        errors.push(`${locator}: no checksum in yarn.lock`)
        continue
    }
    const actual = createHash('sha512').update(readFileSync(join(root, '.yarn/cache', zip))).digest('hex')
    if (actual !== expected) {
        errors.push(`${locator}: checksum mismatch for ${zip}\n  yarn.lock: ${expected}\n  computed:  ${actual}`)
    }
}

if (errors.length > 0) {
    console.error(`pnp cache verification failed:\n${errors.map((e) => `  ${e}`).join('\n')}`)
    process.exit(1)
}
console.log(`pnp cache verification passed: ${referencedZips.size} archives match yarn.lock`)
