"""Repository rule materializing a Yarn PnP zero-install project for Bazel.

This rule never executes Yarn and never synthesizes a node_modules tree. At
repository evaluation it validates the checked-in Yarn graph, lock/config
bindings, integrity-manifest schema, and supported cache/unplugged
classification. The generated pnp_verify_test enforces manifest hashes, file
types, modes, and exact runtime trees. The importer recognizes Yarn's generated
cache and unplugged packageLocation forms; it does not claim to be independent
of those PnP path conventions.
"""

load(":pnp_data.bzl", "pnp_data")
load(":pnp_integrity.bzl", "pnp_integrity")

_DEFS_BZL_TMPL = '''\
"""@generated by pnp_repository; do not edit.

Wraps the checked-in Yarn PnP zero-install artifacts of {root_package_label}
into runnable Bazel targets. See npm/private/pnp/pnp_repository.bzl.
"""

load("@aspect_rules_js//js:defs.bzl", _js_binary = "js_binary", _js_test = "js_test")

# Locator -> {{"zip": ..., "checksum": ..., "dependencies": [...]}} for every
# package in the resolution graph, for introspection and testing.
PNP_PACKAGES = json.decode("""{packages_json}""")

# Everything the PnP runtime needs at execution time: the resolver, its data
# file, lock/config inputs, integrity manifest, offline cache archives, and any
# checked-in unplugged runtime files explicitly supplied by the caller.
PNP_RUNTIME_SRCS = {runtime_srcs}

_PNP_REQUIRE = "--require=./{pnp_cjs_rootpath}"

def pnp_files(name, **kwargs):
    """A filegroup of all checked-in PnP runtime files."""
    native.filegroup(
        name = name,
        srcs = PNP_RUNTIME_SRCS,
        **kwargs
    )

def _pnp_wrap(kwargs):
    kwargs["data"] = kwargs.get("data", []) + PNP_RUNTIME_SRCS
    kwargs["node_options"] = kwargs.get("node_options", []) + [_PNP_REQUIRE]

    # The PnP resolver installs its own fs layer to read modules out of the
    # cache zips; the js_binary fs patches are node_modules-oriented and are
    # not needed here.
    env = dict(kwargs.get("env", {{}}))
    env.setdefault("JS_BINARY__PATCH_NODE_FS", "0")
    kwargs["env"] = env
    return kwargs

def pnp_js_binary(name, **kwargs):
    """A js_binary that resolves dependencies through the checked-in PnP runtime."""
    _js_binary(name = name, **_pnp_wrap(kwargs))

def pnp_js_test(name, **kwargs):
    """A js_test that resolves dependencies through the checked-in PnP runtime."""
    _js_test(name = name, **_pnp_wrap(kwargs))

def pnp_verify_test(name, **kwargs):
    """Verifies every integrity-bound PnP runtime input.

    Recomputes manifest hashes and executable modes before loading the resolver,
    checks exact supported cache and unplugged tree membership, and independently
    cross-checks cache bytes when an active yarn.lock entry carries a checksum.
    Valid no-checksum entries remain protected by the integrity manifest, while
    unplugged packages may retain one lock-backed source archive.
    """
    # Bazel copy actions normalize source modes. Keep source inputs in runfiles
    # so the verifier can compare the executable bit recorded by the manifest.
    if kwargs.get("copy_data_to_bin", False):
        fail("pnp_verify_test requires copy_data_to_bin=False so integrity checks observe source file modes")
    kwargs["copy_data_to_bin"] = False
    _js_test(
        name = name,
        entry_point = "@aspect_rules_js//npm/private/pnp:pnp_verify",
        data = PNP_RUNTIME_SRCS,
        env = {{"PNP_ROOT": "{root_package_path}"}},
        **kwargs
    )
'''

_BUILD_TMPL = '''\
"""@generated by pnp_repository; do not edit."""

exports_files(["defs.bzl"])
'''

def _pnp_repository_impl(rctx):
    lock_content = rctx.read(rctx.attr.yarn_lock)
    pnp_json = rctx.read(rctx.attr.pnp_data)
    pnp_cjs_content = rctx.read(rctx.attr.pnp_cjs)
    manifest = pnp_integrity.parse(rctx.read(rctx.attr.pnp_integrity))

    parsed = pnp_data.parse(pnp_json)
    validated = pnp_data.validate(parsed, lock_content)
    errors = list(validated.errors)
    errors.extend(manifest.errors)
    errors.extend(pnp_integrity.binding_errors(
        pnp_cjs_content,
        rctx.attr.pnp_cjs,
        rctx.attr.pnp_data,
        rctx.attr.pnp_integrity,
        rctx.attr.yarn_lock,
        rctx.attr.yarnrc,
    ))

    manifest_zip_names = {}
    manifest_zip_paths = {}
    manifest_unplugged_roots = {}
    for path in manifest.files:
        if path.endswith(".zip"):
            zip_name = path[path.rfind("/") + 1:]
            manifest_zip_names[zip_name] = True
            manifest_zip_paths[path] = zip_name
        unplugged_marker = path.find("/unplugged/")
        if unplugged_marker != -1:
            child_start = unplugged_marker + len("/unplugged/")
            child_end = path.find("/", child_start)
            if child_end != -1:
                manifest_unplugged_roots[path[:child_end]] = True
    validated_zip_names = {zip_name: True for zip_name in validated.cache_zips}
    unplugged_source_digests = {}
    seen_unplugged_locators = {}
    for package in validated.packages.values():
        locator = package["physical_locator"]
        checksum = package["checksum"]
        if package["unplugged_root"] != None and checksum != None and locator not in seen_unplugged_locators:
            seen_unplugged_locators[locator] = True
            digest = checksum[checksum.rfind("/") + 1:]
            unplugged_source_digests[digest] = locator
    remaining_unplugged_source_digests = dict(unplugged_source_digests)
    for zip_name in validated.cache_zips:
        if zip_name not in manifest_zip_names:
            errors.append("integrity manifest is missing referenced cache archive {}".format(zip_name))
    for path in sorted(manifest_zip_paths.keys()):
        zip_name = manifest_zip_paths[path]
        digest = manifest.files[path]["sha512"]
        if zip_name in validated_zip_names or digest in remaining_unplugged_source_digests:
            if digest in remaining_unplugged_source_digests:
                remaining_unplugged_source_digests.pop(digest)
        else:
            errors.append("integrity manifest cache archive {} is neither graph-referenced nor the unique lock-backed source for an active unplugged package".format(path))
    for digest in sorted(remaining_unplugged_source_digests.keys()):
        errors.append("active unplugged package {} has no cache archive matching yarn.lock checksum {}".format(remaining_unplugged_source_digests[digest], digest))
    validated_unplugged_roots = {root: True for root in validated.unplugged_roots}
    for root in validated.unplugged_roots:
        if not [path for path in manifest.files if path.startswith(root + "/")]:
            errors.append("integrity manifest has no files for unplugged tree {}".format(root))
    for root in sorted(manifest_unplugged_roots.keys()):
        if root not in validated_unplugged_roots:
            errors.append("integrity manifest contains unreferenced unplugged tree {}".format(root))
    if validated.unplugged_roots and not rctx.attr.runtime_files:
        errors.append("runtime_files must include the checked-in unplugged trees: {}".format(", ".join(validated.unplugged_roots)))

    if errors:
        fail("pnp_repository {}: checked-in PnP artifacts are not consistent:\n  {}".format(
            rctx.name,
            "\n  ".join(errors),
        ))

    data_label = rctx.attr.pnp_data
    root_package = "@@{}//{}".format(data_label.workspace_name, data_label.package)

    runtime_srcs = [
        str(rctx.attr.pnp_cjs),
        str(rctx.attr.pnp_data),
        str(rctx.attr.pnp_integrity),
        str(rctx.attr.yarn_lock),
        str(rctx.attr.yarnrc),
        str(rctx.attr.cache),
    ] + [str(label) for label in rctx.attr.runtime_files]

    cjs_label = rctx.attr.pnp_cjs
    pnp_cjs_rootpath = "/".join([p for p in [cjs_label.package, cjs_label.name] if p])

    rctx.file("defs.bzl", _DEFS_BZL_TMPL.format(
        root_package_label = root_package,
        packages_json = json.encode_indent(validated.packages, indent = "  "),
        runtime_srcs = json.encode_indent(runtime_srcs, indent = "  "),
        pnp_cjs_rootpath = pnp_cjs_rootpath,
        root_package_path = data_label.package if data_label.package else ".",
    ))
    rctx.file("BUILD.bazel", _BUILD_TMPL)

pnp_repository = repository_rule(
    implementation = _pnp_repository_impl,
    attrs = {
        "cache": attr.label(
            doc = "A checked-in filegroup containing the Yarn offline cache archives listed by .pnp.integrity.json.",
            mandatory = True,
        ),
        "pnp_cjs": attr.label(
            doc = "The checked-in .pnp.cjs resolver generated by `yarn install`.",
            mandatory = True,
            allow_single_file = True,
        ),
        "pnp_data": attr.label(
            doc = "The checked-in .pnp.data.json file generated by `yarn install` with `pnpEnableInlining: false`.",
            mandatory = True,
            allow_single_file = True,
        ),
        "pnp_integrity": attr.label(
            doc = "The checked-in .pnp.integrity.json file binding the resolver, data, config, cache, and unplugged files.",
            mandatory = True,
            allow_single_file = True,
        ),
        "runtime_files": attr.label_list(
            doc = "Checked-in filegroups needed by packageLocations outside cache zips, such as .yarn/unplugged trees.",
        ),
        "yarn_lock": attr.label(
            doc = "The checked-in Yarn Berry yarn.lock file.",
            mandatory = True,
            allow_single_file = True,
        ),
        "yarnrc": attr.label(
            doc = "The checked-in .yarnrc.yml whose PnP and package-extension settings produced the data file.",
            mandatory = True,
            allow_single_file = True,
        ),
    },
    doc = "Consumes a checked-in Yarn PnP zero-install project without running Yarn.",
)
