# This workspace is loaded as a local_repository
workspace(name = "rules_foo")

local_repository(
    name = "aspect_rules_js",
    path = "../../..",
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")

rules_js_dependencies()

load("@rules_nodejs//nodejs:repositories.bzl", "nodejs_register_toolchains")

nodejs_register_toolchains(
    name = "nodejs",
    node_version = "16.9.0",
)

load("@aspect_bazel_lib//lib:repositories.bzl", "DEFAULT_YQ_VERSION", "register_yq_toolchains")

register_yq_toolchains(
    version = DEFAULT_YQ_VERSION,
)

load("@rules_foo//:repositories.bzl", rules_foo_repositories = "repositories")

rules_foo_repositories()
