load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
    name = "aspect_rules_js",
    path = "../..",
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")

rules_js_dependencies()

load("@aspect_rules_js//js:toolchains.bzl", "DEFAULT_NODE_VERSION", "rules_js_register_toolchains")

rules_js_register_toolchains(node_version = DEFAULT_NODE_VERSION)

http_archive(
    name = "rules_shell",
    sha256 = "e6b87c89bd0b27039e3af2c5da01147452f240f75d505f5b6880874f31036307",
    strip_prefix = "rules_shell-0.6.1",
    url = "https://github.com/bazelbuild/rules_shell/releases/download/v0.6.1/rules_shell-v0.6.1.tar.gz",
)

load("@aspect_rules_js//npm:repositories.bzl", "npm_import")

npm_import(
    name = "protoc-gen-grpc",
    commit = "be5580b06348d3eb9b4610a4a94065154a0df41f",
    package = "protoc-gen-grpc",
    root_package = "",
    url = "git+ssh://git@github.com/gregmagolan-codaio/protoc-gen-grpc-ts.git",
    version = "github.com/gregmagolan-codaio/protoc-gen-grpc-ts/be5580b06348d3eb9b4610a4a94065154a0df41f",
)

npm_import(
    name = "syncpack",
    commit = "c245af8ea73ce3345d92bbda6c684092a841e262",
    package = "syncpack",
    root_package = "",
    url = "https://git@github.com/JamieMason/syncpack.git",
    version = "c245af8ea73ce3345d92bbda6c684092a841e262",
)
