local_repository(
    name = "aspect_rules_js",
    path = "../..",
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")

rules_js_dependencies()

load("@aspect_rules_js//js:configure.bzl", "rules_js_register_toolchains")

rules_js_register_toolchains()

load("@aspect_rules_js//npm:repositories.bzl", "npm_import")

npm_import(
    name = "protoc-gen-grpc",
    commit = "be5580b06348d3eb9b4610a4a94065154a0df41f",
    package = "protoc-gen-grpc",
    root_package = "",
    url = "git+ssh://git@github.com/gregmagolan-codaio/protoc-gen-grpc-ts.git",
    version = "github.com/gregmagolan-codaio/protoc-gen-grpc-ts/be5580b06348d3eb9b4610a4a94065154a0df41f",
)

npm_import(
    name = "syncpack",
    commit = "c245af8ea73ce3345d92bbda6c684092a841e262",
    package = "syncpack",
    root_package = "",
    url = "https://codeload.github.com/JamieMason/syncpack/tar.gz/c245af8ea73ce3345d92bbda6c684092a841e262",
    version = "github.com/JamieMason/syncpack/c245af8ea73ce3345d92bbda6c684092a841e262",
)
