load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

###
# Setup rules_js
###
local_repository(
    name = "aspect_rules_js",
    path = "../..",
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")

rules_js_dependencies()

load("@aspect_rules_js//js:toolchains.bzl", "rules_js_register_toolchains")

rules_js_register_toolchains(node_version_from_nvmrc = "//:.nvmrc")

load("@aspect_rules_js//npm:repositories.bzl", "npm_translate_lock")

npm_translate_lock(
    name = "npm",
    npmrc = "//:.npmrc",
    pnpm_lock = "//:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
)

load("@npm//:repositories.bzl", "npm_repositories")

npm_repositories()

###
# Setup rules_docker
# rules_docker does not work with M1 macs due to ancient rules_go version.
###
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "b1e80761a8a8243d03ebca8845e9cc1ba6c82ce7c5179ce2b295cd36f7e394bf",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.25.0/rules_docker-v0.25.0.tar.gz"],
)

# WORKAROUND START
# This is workaround for M1 users and should be removed once https://github.com/bazelbuild/rules_docker/issues/2036 is fixed.
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "80a98277ad1311dacd837f9b16db62887702e9f1d1c4c9f796d0121a46c8e184",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/v0.46.0/rules_go-v0.46.0.zip"],
)

# Bring in a newer version of bazel_gazelle to work-around an incompatability with an older
# version that is brought in transitively below that is incompatible with newer versions of rules_go.
# Error when this is not done is:
# ERROR: Traceback (most recent call last):
# 	File "/private/var/tmp/_bazel_greg/970c650b0c043c16acaced625553237d/external/bazel_gazelle/internal/go_repository_tools.bzl", line 15, column 52, in <toplevel>
# 		load("@io_bazel_rules_go//go/private:common.bzl", "env_execute", "executable_extension")
# Error: file '@io_bazel_rules_go//go/private:common.bzl' does not contain symbol 'env_execute'
# ERROR: Error computing the main repository mapping: at /private/var/tmp/_bazel_greg/970c650b0c043c16acaced625553237d/external/io_bazel_rules_docker/repositories/deps.bzl:22:6: at /private/var/tmp/_bazel_greg/970c650b0c043c16acaced625553237d/external/io_bazel_rules_docker/repositories/go_repositories.bzl:22:6: at /private/var/tmp/_bazel_greg/970c650b0c043c16acaced625553237d/external/bazel_gazelle/deps.bzl:24:5: initialization of module 'internal/go_repository_tools.bzl' failed
http_archive(
    name = "bazel_gazelle",
    integrity = "sha256-dd8ojEsxyB61D1Hi4U9HY8t1SNquEmgXJHBkY3/Z6mI=",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.36.0/bazel-gazelle-v0.36.0.tar.gz"],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(version = "1.20.5")
# WORKAROUND END

load("@io_bazel_rules_docker//repositories:repositories.bzl", rules_docker_repositories = "repositories")

rules_docker_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", rules_docker_deps = "deps")

rules_docker_deps()

load("@io_bazel_rules_docker//container:container.bzl", "container_pull")

container_pull(
    name = "debian_arm64",
    architecture = "arm64",
    digest = "sha256:bd276cb1059f6502e342d3052a4c2767f2b3a0196508f5c2c34ce6da4a15b104",
    registry = "docker.io",
    repository = "debian",
)

container_pull(
    name = "debian_amd64",
    architecture = "amd64",
    digest = "sha256:9a67b70d0ba1d7c7690f917eedd8d24974dd8fd493205368b1e555a90c954208",
    registry = "docker.io",
    repository = "debian",
)
