local_repository(
    name = "aspect_rules_js",
    path = "../..",
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")

rules_js_dependencies()

load("@aspect_rules_js//js:toolchains.bzl", "DEFAULT_NODE_VERSION", "rules_js_register_toolchains")

rules_js_register_toolchains(node_version = DEFAULT_NODE_VERSION)

load("@rules_nodejs//nodejs:repositories.bzl", "nodejs_register_toolchains")

nodejs_register_toolchains(
    name = "nodejs",
    node_version = DEFAULT_NODE_VERSION,
)

load("@aspect_rules_js//npm:repositories.bzl", "npm_translate_lock")

[
    npm_translate_lock(
        name = "lock-%s" % version,
        data = [
            "//:package.json",
            "//%s:patches/meaning-of-life@1.0.0-pnpm.patch" % version,
            "//:pnpm-workspace.yaml",
        ],
        npmrc = "//:.npmrc",
        patch_args = {"*": ["-p1"]},
        pnpm_lock = "//%s:pnpm-lock.yaml" % version,
        verify_node_modules_ignored = "//:.bazelignore",
    )
    for version in [
        "v53",
        "v54",
        "v60",
        "v61",
    ]
]

load("@lock-v53//:repositories.bzl", npm_repositories_v53 = "npm_repositories")
load("@lock-v54//:repositories.bzl", npm_repositories_v54 = "npm_repositories")
load("@lock-v60//:repositories.bzl", npm_repositories_v60 = "npm_repositories")
load("@lock-v61//:repositories.bzl", npm_repositories_v61 = "npm_repositories")

npm_repositories_v53()

npm_repositories_v54()

npm_repositories_v60()

npm_repositories_v61()
