load("@aspect_rules_js//js:defs.bzl", "js_binary", "js_run_binary")
load("@bazel_skylib//rules:build_test.bzl", "build_test")

# Verifies that a js_run_binary target supports path mapping. This requires
# set_legacy_environment_variables to be disabled, and args must avoid Make
# variable and location expansion.
js_binary(
    name = "check",
    entry_point = "check.mjs",
)

js_run_binary(
    name = "js_run_binary_path_mapping_check",
    outs = ["out.txt"],
    args = ["out.txt"],
    chdir = package_name(),
    mnemonic = "JsRunBinaryPathMappingCheck",
    set_legacy_environment_variables = False,
    tool = ":check",
)

build_test(
    name = "js_run_binary_path_mapping_check_test",
    targets = [":js_run_binary_path_mapping_check"],
)
