const leftPad = require('left-pad')
const isOdd = require('is-odd')
const React = require('react')
const ReactDom = require('react-dom')
const assert = require('node:assert')
assert.strictEqual(leftPad('7', 3, '0'), '007')
assert.strictEqual(isOdd(7), true)
assert.strictEqual(React.version, '19.2.4')
assert.strictEqual(typeof ReactDom.createPortal, 'function')
console.log('pnp-zero-install-ok')
