"""Private rule for transforming package.json to resolve pnpm workspace protocols."""

PnpmPackageInfo = provider(
    doc = "Version information for a pnpm workspace package, provided by pnpm_package_json_transform",
    fields = {
        "package_json": "The transformed package.json File containing the resolved name and version",
    },
)

_TransitivePnpmPackageInfos = provider(
    doc = "Collects PnpmPackageInfo from the transitive dependency graph",
    fields = {
        "package_jsons": "depset of transformed package.json Files from workspace deps",
    },
)

def _collect_workspace_versions_aspect_impl(target, ctx):
    direct = []
    if PnpmPackageInfo in target:
        direct.append(target[PnpmPackageInfo].package_json)

    transitive = []
    for attr_name in ["srcs", "deps", "src"]:
        deps = getattr(ctx.rule.attr, attr_name, None)
        if deps == None:
            continue
        # label_keyed_string_dict attrs produce a dict, label_list attrs produce a list
        targets = deps.keys() if type(deps) == "dict" else deps
        for dep in targets:
            if _TransitivePnpmPackageInfos in dep:
                transitive.append(dep[_TransitivePnpmPackageInfos].package_jsons)

    return [_TransitivePnpmPackageInfos(
        package_jsons = depset(direct, transitive = transitive),
    )]

_collect_workspace_versions_aspect = aspect(
    implementation = _collect_workspace_versions_aspect_impl,
    attr_aspects = ["srcs", "deps", "src"],
)

def _pnpm_package_json_transform_impl(ctx):
    if ctx.attr.version and ctx.file.version_file:
        fail("Only one of version or version_file may be specified")

    output = ctx.actions.declare_file(ctx.label.name + "/package.json")

    args = ctx.actions.args()
    args.add("--catalogs-json", ctx.file.pnpm_catalogs)
    args.add("--package-json", ctx.file.package_json)
    args.add("--output", output)

    version = ctx.attr.version
    if version and ctx.attr.stamped:
        version = "{}-{}-{}".format(
            version,
            ctx.var["BUILD_TIMESTAMP"],
            ctx.var["SHORT_GIT_COMMIT"],
        )

    if version:
        args.add("--version", version)
    elif ctx.file.version_file:
        args.add("--version-file", ctx.file.version_file)

    if ctx.file.pnpm_workspace_versions:
        args.add("--workspace-versions-json", ctx.file.pnpm_workspace_versions)

    inputs = [ctx.file.pnpm_catalogs, ctx.file.package_json]
    if ctx.file.version_file:
        inputs.append(ctx.file.version_file)
    if ctx.file.pnpm_workspace_versions:
        inputs.append(ctx.file.pnpm_workspace_versions)

    # Collect workspace dep versions from explicit workspace_deps
    for dep in ctx.attr.workspace_deps:
        dep_pj = dep[PnpmPackageInfo].package_json
        args.add("--workspace-dep-package-json", dep_pj)
        inputs.append(dep_pj)

    # Collect workspace dep versions discovered via aspect on srcs
    seen = {}
    for src in ctx.attr.srcs:
        if _TransitivePnpmPackageInfos in src:
            for pj in src[_TransitivePnpmPackageInfos].package_jsons.to_list():
                if pj.path not in seen:
                    seen[pj.path] = True
                    args.add("--workspace-dep-package-json", pj)
                    inputs.append(pj)

    ctx.actions.run(
        executable = ctx.executable._transform_tool,
        arguments = [args],
        inputs = inputs,
        outputs = [output],
        env = {"BAZEL_BINDIR": ctx.bin_dir.path},
    )

    return [
        DefaultInfo(files = depset([output])),
        PnpmPackageInfo(package_json = output),
    ]

pnpm_package_json_transform = rule(
    implementation = _pnpm_package_json_transform_impl,
    attrs = {
        "package_json": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "The package.json file to transform",
        ),
        "pnpm_catalogs": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "The catalogs JSON file, generated by npm_translate_lock or pnpm_extract_catalogs",
        ),
        "pnpm_workspace_versions": attr.label(
            allow_single_file = True,
            doc = "JSON file mapping workspace package names to versions, generated by npm_translate_lock",
        ),
        "workspace_deps": attr.label_list(
            providers = [PnpmPackageInfo],
            doc = "Explicit workspace dep targets whose versions override workspace_versions.json",
        ),
        "srcs": attr.label_list(
            allow_files = True,
            aspects = [_collect_workspace_versions_aspect],
            doc = "Sources to scan for transitive PnpmPackageInfo providers via aspect",
        ),
        "stamped": attr.bool(
            default = False,
            doc = "When True, appends BUILD_TIMESTAMP-SHORT_GIT_COMMIT to the version",
        ),
        "version": attr.string(
            doc = "Override the version in the output package.json",
        ),
        "version_file": attr.label(
            allow_single_file = True,
            doc = "A file containing the version string. Alternative to the version string attribute.",
        ),
        "_transform_tool": attr.label(
            executable = True,
            cfg = "exec",
            default = "@aspect_rules_js//npm/private:pnpm_package_json_transform_bin",
        ),
    },
    doc = "Transforms package.json to resolve pnpm workspace protocols (catalog:, workspace:, etc.)",
)
