"""Rule for building npm packages in pnpm workspaces.

Wraps the upstream npm_package rule, adding a build-time transform that resolves
pnpm workspace protocols (catalog:, workspace:, etc.) in package.json, mirroring
what pnpm publish does before packing.

Load with:

```starlark
load("@aspect_rules_js//npm:defs.bzl", "pnpm_package")
```
"""

load(":npm_package.bzl", _npm_package = "npm_package")
load(":pnpm_package_json_transform.bzl", _pnpm_package_json_transform = "pnpm_package_json_transform")

def _runfiles_path(ctx, f):
    p = f.short_path
    if p.startswith("../"):
        return p[3:]
    return ctx.workspace_name + "/" + p

def _pnpm_publish_impl(ctx):
    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")

    pnpm_bin = ctx.executable._pnpm
    pkg_dir = ctx.attr.pkg[DefaultInfo].files.to_list()[0]

    pnpm_path = _runfiles_path(ctx, pnpm_bin)
    pkg_path = _runfiles_path(ctx, pkg_dir)

    ctx.actions.write(
        output = launcher,
        content = """\
#!/usr/bin/env bash
set -euo pipefail

# Resolve the runfiles directory
if [[ -d "$0.runfiles" ]]; then
    RUNFILES="$0.runfiles"
elif [[ "${{RUNFILES_DIR:-}}" ]]; then
    RUNFILES="${{RUNFILES_DIR}}"
else
    echo >&2 "ERROR: Cannot find runfiles directory"
    exit 1
fi

exec "${{RUNFILES}}/{pnpm}" publish --no-git-checks "${{RUNFILES}}/{pkg}" {extra_args} "$@"
""".format(
            pnpm = pnpm_path,
            pkg = pkg_path,
            extra_args = " ".join(["'%s'" % a for a in ctx.attr.extra_args]),
        ),
        is_executable = True,
    )

    runfiles = ctx.runfiles(files = [launcher, pkg_dir])
    runfiles = runfiles.merge(ctx.attr._pnpm[DefaultInfo].default_runfiles)
    runfiles = runfiles.merge(ctx.attr.pkg[DefaultInfo].default_runfiles)

    return [DefaultInfo(
        executable = launcher,
        runfiles = runfiles,
    )]

_pnpm_publish = rule(
    implementation = _pnpm_publish_impl,
    executable = True,
    attrs = {
        "pkg": attr.label(
            mandatory = True,
            doc = "The npm_package target to publish",
        ),
        "extra_args": attr.string_list(
            doc = "Additional arguments passed to pnpm publish",
        ),
        "_pnpm": attr.label(
            executable = True,
            cfg = "target",
            default = "@pnpm//:pnpm",
        ),
    },
)

def _is_label(value):
    """Returns True if value looks like a Bazel label rather than a plain string."""
    return value.startswith(":") or value.startswith("//") or value.startswith("@")

def _to_transform_label(dep):
    """Convert a pnpm_package label to its internal transform target label."""
    if ":" in dep:
        return dep + "_package_json"
    last = dep.split("/")[-1]
    return dep + ":" + last + "_package_json"

def pnpm_package(
        name,
        srcs,
        pnpm_catalogs = "@npm//:catalogs.json",
        package_json = "package.json",
        pnpm_workspace_versions = "@npm//:workspace_versions.json",
        workspace_deps = [],
        version = None,
        stamped = False,
        publishable = False,
        tag = "latest",
        **kwargs):
    """Creates an npm package with pnpm-compatible package.json transforms.

    Wraps the upstream rules_js npm_package rule, adding a build-time transform
    that resolves pnpm workspace protocols (catalog:, workspace:, etc.) in
    package.json, mirroring what pnpm publish does before packing.

    Both catalog and workspace protocol resolution use JSON files generated
    automatically by npm_translate_lock:
    - `@npm//:catalogs.json` — catalog definitions from pnpm-workspace.yaml
    - `@npm//:workspace_versions.json` — workspace package name-to-version mapping

    With the defaults, no explicit configuration is needed:

    ```starlark
    pnpm_package(
        name = "my_package",
        srcs = [":my_lib"],
    )
    ```

    When workspace packages derive their version at build time (e.g. from git
    tags) rather than from the source package.json, use `workspace_deps` to
    reference those packages. Their resolved versions override the base
    workspace_versions.json entries:

    ```starlark
    pnpm_package(
        name = "my_consumer",
        srcs = [":my_lib"],
        workspace_deps = [
            "//packages/dep-a",
            "//packages/dep-b",
        ],
    )
    ```

    The version can be a string literal or a label to a file containing the version:

    ```starlark
    pnpm_package(
        name = "my_package",
        srcs = [":my_lib"],
        version = ":version_from_git_tag",
    )
    ```

    Args:
        name: Target name
        srcs: Source files to include in the package (excluding package.json)
        pnpm_catalogs: Label of the catalogs JSON file. Defaults to @npm//:catalogs.json
            generated by npm_translate_lock.
        package_json: The package.json file to transform (default: "package.json")
        pnpm_workspace_versions: Label of the workspace_versions.json generated by
            npm_translate_lock. Used as the base for resolving workspace: protocols.
        workspace_deps: Labels of other pnpm_package targets in the workspace. Their
            resolved versions override entries in workspace_versions.json, ensuring
            consumers get the correct build-time version even when source package.json
            files use placeholder versions like "0.0.0-development".
        version: Override the version in the output package.json. Either a version string
            (e.g. "1.2.3") or a label to a file containing the version (e.g. ":version").
        stamped: When True, appends BUILD_TIMESTAMP-SHORT_GIT_COMMIT to the version
        publishable: When True, also creates a {name}.publish target
        tag: The dist-tag to use when publishing (default: "latest")
        **kwargs: Additional arguments passed to the upstream npm_package rule
    """
    transform_name = name + "_package_json"

    version_string = None
    version_file = None
    if version and _is_label(version):
        version_file = version
    elif version:
        version_string = version

    transform_kwargs = {}
    if version_string:
        transform_kwargs["version"] = version_string
    if version_file:
        transform_kwargs["version_file"] = version_file
    if stamped:
        transform_kwargs["stamped"] = True

    if pnpm_workspace_versions:
        transform_kwargs["pnpm_workspace_versions"] = pnpm_workspace_versions

    if workspace_deps:
        transform_kwargs["workspace_deps"] = [_to_transform_label(dep) for dep in workspace_deps]

    _pnpm_package_json_transform(
        name = transform_name,
        package_json = package_json,
        pnpm_catalogs = pnpm_catalogs,
        srcs = srcs,
        tags = kwargs.get("tags", []) + ["manual"],
        **transform_kwargs
    )

    if publishable:
        _pnpm_publish(
            name = "{}.publish".format(name),
            pkg = name,
            extra_args = ["--tag", tag],
            tags = kwargs.get("tags", []) + ["manual"],
            testonly = kwargs.get("testonly", False),
            visibility = kwargs.get("visibility", None),
        )

    replace_prefixes = dict(kwargs.pop("replace_prefixes", {}))
    replace_prefixes[transform_name + "/"] = ""

    npm_package_kwargs = dict(kwargs)
    if version_string:
        npm_package_kwargs["version"] = version_string

    _npm_package(
        name = name,
        srcs = srcs + [":" + transform_name],
        replace_prefixes = replace_prefixes,
        **npm_package_kwargs
    )
