local_repository(
    name = "aspect_rules_js",
    path = "../..",
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")

rules_js_dependencies()

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# See comment in README about these fetches
http_archive(
    name = "vendored_node_linux_amd64",
    build_file_content = """exports_files(["bin/node"])""",
    sha256 = "cc9c3eed21755b490e5333ccab208ce15b539c35f64a764eeeae77c58746a7ff",
    strip_prefix = "node-v15.0.1-linux-x64",
    urls = ["https://nodejs.org/dist/v15.0.1/node-v15.0.1-linux-x64.tar.xz"],
)

http_archive(
    name = "vendored_node_darwin_amd64",
    build_file_content = """exports_files(["bin/node"])""",
    sha256 = "78571df5b35d3ec73d7543332776bcb8cab3bc0e3abd12b1440fbcd01c74c055",
    strip_prefix = "node-v15.0.1-darwin-x64",
    urls = ["https://nodejs.org/dist/v15.0.1/node-v15.0.1-darwin-x64.tar.xz"],
)

http_archive(
    name = "vendored_node_windows_amd64",
    build_file_content = """exports_files(["node.exe"])""",
    sha256 = "efa7a74d91789a6e9f068f375e49f108ff87578fd88ff4b4e7fefd930c04db6c",
    strip_prefix = "node-v15.0.1-win-x64",
    urls = ["https://nodejs.org/dist/v15.0.1/node-v15.0.1-win-x64.zip"],
)

register_toolchains("//toolchains:all")
