local_repository(
    name = "aspect_rules_js",
    path = "../..",
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")

rules_js_dependencies()

load("@aspect_rules_js//js:configure.bzl", "rules_js_register_toolchains")

rules_js_register_toolchains(register_nodejs_toolchain = False)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "vendored_node_linux_amd64",
    build_file_content = """exports_files(["bin/node"])""",
    sha256 = "de2c694e7081c37022817d27a65b02f69ecf4c49699d65585e8e24431b7bc920",
    strip_prefix = "node-v16.18.1-linux-x64",
    urls = ["https://nodejs.org/download/release/v16.18.1/node-v16.18.1-linux-x64.tar.xz"],
)

http_archive(
    name = "vendored_node_darwin_amd64",
    build_file_content = """exports_files(["bin/node"])""",
    sha256 = "79ff9ca43ae882051b2d607696cb3e70bfdef8c7b24f8d3effa3d41ff16368ff",
    strip_prefix = "node-v16.18.1-darwin-x64",
    urls = ["https://nodejs.org/download/release/v16.18.1/node-v16.18.1-darwin-x64.tar.xz"],
)

http_archive(
    name = "vendored_node_windows_amd64",
    build_file_content = """exports_files(["node.exe"])""",
    sha256 = "db6a81de8e8ca3444495f1bcf04a883c076b4325d0fbaa032a190f88b38b30c5",
    strip_prefix = "node-v16.18.1-win-x64",
    urls = ["https://nodejs.org/download/release/v16.18.1/node-v16.18.1-win-x64.zip"],
)

register_toolchains("//toolchains:all")
