name: Add to Aspect OSS Bazel Rules project when opened
on:
    issues:
        types:
            - opened
            - reopened
jobs:
    comment:
        runs-on: ubuntu-latest
        steps:
            - run: |
                  gh api graphql -f query='
                    mutation {
                      addProjectV2ItemById(input: {projectId: "$PROJECT_ID" contentId: "$ISSUE_ID"}) {
                        item {
                          id
                        }
                      }
                    }
                  '
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_PROJECTS_RW_TOKEN }}
                  OWNER: ${{ github.repository_owner }}
                  REPO: ${{ github.event.repository.name }}
                  ISSUE_ID: ${{ github.event.issue.node_id }}
                  # Project: Aspect OSS Bazel Rules
                  PROJECT_ID: PVT_kwDOA6IKMs4ALj2o
