"""@generated by npm_translate_lock(name = "npm", pnpm_lock = "//:pnpm-lock.yaml")"""

load("@aspect_rules_js//npm:repositories.bzl", "npm_import")

# Generated npm_import repository rules corresponding to npm packages in //:pnpm-lock.yaml
# buildifier: disable=function-docstring
def npm_repositories():
    npm_import(
        name = "npm__debug__registry.npmjs.org_debug_4.3.4",
        root_package = "",
        link_workspace = "",
        link_packages = {
            "": ["debug"],
        },
        package = "debug",
        version = "registry.npmjs.org/debug@4.3.4",
        url = "https://registry.yarnpkg.com/debug/-/debug-4.3.4.tgz",
        package_visibility = ["//visibility:public"],
        integrity = "sha512-PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==",
        deps = {
            "ms": "registry.npmjs.org/ms@2.1.2",
        },
        transitive_closure = {
            "debug": ["registry.npmjs.org/debug@4.3.4"],
            "ms": ["registry.npmjs.org/ms@2.1.2"],
        },
    )

    npm_import(
        name = "npm__is-number__registry.npmjs.org_is-number_6.0.0",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "is-number",
        version = "registry.npmjs.org/is-number@6.0.0",
        url = "https://registry.yarnpkg.com/is-number/-/is-number-6.0.0.tgz",
        package_visibility = ["//visibility:public"],
        integrity = "sha512-Wu1VHeILBK8KAWJUAiSZQX94GmOE45Rg6/538fKwiloUu21KncEkYGPqob2oSZ5mUT73vLGrHQjKw3KMPwfDzg==",
        transitive_closure = {
            "is-number": ["registry.npmjs.org/is-number@6.0.0"],
        },
    )

    npm_import(
        name = "npm__is-odd__registry.npmjs.org_is-odd_3.0.1",
        root_package = "",
        link_workspace = "",
        link_packages = {
            "": ["is-odd"],
        },
        package = "is-odd",
        version = "registry.npmjs.org/is-odd@3.0.1",
        url = "https://registry.yarnpkg.com/is-odd/-/is-odd-3.0.1.tgz",
        package_visibility = ["//visibility:public"],
        integrity = "sha512-CQpnWPrDwmP1+SMHXZhtLtJv90yiyVfluGsX5iNCVkrhQtU3TQHsUWPG9wkdk9Lgd5yNpAg9jQEo90CBaXgWMA==",
        deps = {
            "is-number": "registry.npmjs.org/is-number@6.0.0",
        },
        transitive_closure = {
            "is-number": ["registry.npmjs.org/is-number@6.0.0"],
            "is-odd": ["registry.npmjs.org/is-odd@3.0.1"],
        },
    )

    npm_import(
        name = "npm__lru-cache__registry.npmjs.org_lru-cache_6.0.0",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "lru-cache",
        version = "registry.npmjs.org/lru-cache@6.0.0",
        url = "https://registry.yarnpkg.com/lru-cache/-/lru-cache-6.0.0.tgz",
        package_visibility = ["//visibility:public"],
        integrity = "sha512-Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==",
        deps = {
            "yallist": "registry.npmjs.org/yallist@4.0.0",
        },
        transitive_closure = {
            "lru-cache": ["registry.npmjs.org/lru-cache@6.0.0"],
            "yallist": ["registry.npmjs.org/yallist@4.0.0"],
        },
    )

    npm_import(
        name = "npm__ms__registry.npmjs.org_ms_2.1.2",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "ms",
        version = "registry.npmjs.org/ms@2.1.2",
        url = "https://registry.yarnpkg.com/ms/-/ms-2.1.2.tgz",
        package_visibility = ["//visibility:public"],
        integrity = "sha512-sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==",
        transitive_closure = {
            "ms": ["registry.npmjs.org/ms@2.1.2"],
        },
    )

    npm_import(
        name = "npm__semver__registry.npmjs.org_semver_7.5.1",
        root_package = "",
        link_workspace = "",
        link_packages = {
            "": ["semver"],
        },
        package = "semver",
        version = "registry.npmjs.org/semver@7.5.1",
        url = "https://registry.yarnpkg.com/semver/-/semver-7.5.1.tgz",
        package_visibility = ["//visibility:public"],
        integrity = "sha512-Wvss5ivl8TMRZXXESstBA4uR5iXgEN/VC5/sOcuXdVLzcdkz4HWetIoRfG5gb5X+ij/G9rw9YoGn3QoQ8OCSpw==",
        deps = {
            "lru-cache": "registry.npmjs.org/lru-cache@6.0.0",
        },
        transitive_closure = {
            "lru-cache": ["registry.npmjs.org/lru-cache@6.0.0"],
            "semver": ["registry.npmjs.org/semver@7.5.1"],
            "yallist": ["registry.npmjs.org/yallist@4.0.0"],
        },
    )

    npm_import(
        name = "npm__yallist__registry.npmjs.org_yallist_4.0.0",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "yallist",
        version = "registry.npmjs.org/yallist@4.0.0",
        url = "https://registry.yarnpkg.com/yallist/-/yallist-4.0.0.tgz",
        package_visibility = ["//visibility:public"],
        integrity = "sha512-3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==",
        transitive_closure = {
            "yallist": ["registry.npmjs.org/yallist@4.0.0"],
        },
    )
